### ISSUE TITLE
Add SegTracker to debugger

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#101]
Consider merging lallafa's segracker support:
http://lallafa.de/blog/2013/06/added-segtracker-in-fs-uaes-debugger/

**Comment by cahirwpz** [comment]
Great enhancement! Are there any chances it will be integrated soon? Could @cnvogelg help you with that?

**Comment by cnvogelg** [comment]
Sure, I have the patch moved along the dev releases on my branch (as I still use it regularly). I can prepare a pull request if Frode is interested.

**Comment by FrodeSolheim** [comment]
Yes, I am interested in / positive to merging this functionality, especially if it is relatively non-intrusive into existing UAE code (so it does not make merging WinUAE code significantly harder). @cnvogelg If you create a pull request, I'll be happy to look at it (I'll have time in the weekend).

**Comment by cnvogelg** [comment]
done. see #112

**Comment by FrodeSolheim** [comment]
Merged :)
