### ISSUE TITLE
Ability to name save states

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#102]

**Comment by reddwarf4ever** [comment]
agree

**Comment by hamakei** [comment]
I'd like to see this as well. Especially when coming back to FS-UAE after some time, being presented with a list of dates isn't very helpful when trying to work out which ones are which games.

**Comment by MarkSpizu** [comment]
What happened with ability to name save states?

**Comment by FrodeSolheim** [comment]
For the next version of FS-UAE, I'm planning to add support for automatic screenshot/thumbnail for save states. It might not be worth the effort to implement UI for labeling the states as well.

**Comment by hamakei** [comment]
That would be good...I think for many people a thumbnail would be sufficient...

Personally I tend to use the save states for different games within a WHDLoad installation...so I can't tell which is which purely by date and time..

**Comment by FrodeSolheim** [comment]
Closing this and will focus on https://github.com/FrodeSolheim/fs-uae/issues/103 instead
