### ISSUE TITLE
Incorrect FSF address

### ISSUE THREAD

**Issue by musuruan** [FrodeSolheim/fs-uae#107]
The FSF address contained in these files is outdated:

/usr/share/fs-uae/shaders/scale4xhq.shader
/src/od-fs/bsdsocket_posix.cpp
/src/cpummu.cpp
/src/include/cpummu.h
/src/include/fsusage.h
/src/fsusage.cpp

These files have been reported by rpmlint after making an RPM. There may be more.

The correct address is written here:
http://www.fsf.org/about/contact/

**Comment by FrodeSolheim** [comment]
Fixed in https://github.com/FrodeSolheim/fs-uae/commit/f4a8c7033c5ab11ac857575efc0902b27b8e3249
