### ISSUE TITLE
FTBFS with GCC 6: narrowing conversion

### ISSUE THREAD

**Issue by musuruan** [FrodeSolheim/fs-uae#108]
FS-UAE 2.6.2 cannot be compiled with GCC6.

For details please see this Debian bug report:
https://bugs.debian.org/811779

I got the same result when trying to compile it on Fedora Rawhide.

**Comment by FrodeSolheim** [comment]
Hi, you can probably compile with -std=gnu++98 (in CXXFLAGS) until the problem has been resolved.

**Comment by FrodeSolheim** [comment]
More information: https://gcc.gnu.org/gcc-6/porting_to.html

> The C++11 standard does not allow "narrowing conversions" inside braced initialization lists, meaning conversions to a type with less precision or a smaller range

**Comment by FrodeSolheim** [comment]
There was a narrowing conversion error when compiling the development version on Fedora 24. I have fixed this in https://github.com/FrodeSolheim/fs-uae/commit/f7bf7b79c231769b0b4c2c59f35aae1fd84d2d1f. I will not be doing any GCC 6-related fixes for 2.6.x, since a new stable version is imminent.

**Comment by glaubitz** [comment]
This patch isn't enough, there are still problems with incorrectly declared variables in "struct expansionromtype", just applying your patch still results in an FTBFS on Debian with gcc-6:

src/expansion.cpp:2537:1: error: narrowing conversion of '2148532239u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
 };
 ^
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532225u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532230u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532232u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532237u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532238u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532244u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532241u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532250u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532251u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532252u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532253u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2537:1: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
src/expansion.cpp:2537:1: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
src/expansion.cpp:2537:1: error: narrowing conversion of '2148532233u' from 'unsigned int' to 'int' inside { } [-Wnarrowing]
src/expansion.cpp:2859:1: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
 };
 ^
Makefile:4156: recipe for target 'src/expansion.o' failed

**Comment by glaubitz** [comment]
Also, I suggest using "uae_u32" instead of "unsigned int" since the latter is not guaranteed to be 32 bits wide which is why "uae_u32" has actually been declared in src/include/uae/types.h.

**Comment by glaubitz** [comment]
WinUAE upstream has actually fixed the problem in src/include/autoconf.h by using uae_u32 instead of "unsigned int", see 6908c626.
