### ISSUE TITLE
Remote command invocation for running automated tests

### ISSUE THREAD

**Issue by cahirwpz** [FrodeSolheim/fs-uae#111]
I'm planning to integrate execution of gcc testsuite for [amigaos-cross-toolchain](https://github.com/cahirwpz/amigaos-cross-toolchain) project. About 33% of tests require to be executed on real machine / emulator to pass. I'm looking for a way to achieve that in the most convenient manner. IMO the best option would be to run test binaries in emulated environment.

I've tried to use *vamos* from [amitools](https://github.com/cnvogelg/amitools) by @cnvogelg, but it misses implementation of some important and non-trivial library calls (namely `Allocate` from `exec.library`) and I'd expect to discover more problems in the future. If *vamos* implemented all required features it'd preferred solution to my problem.

I looked at other options and I found out that *UAE* should be able to run commands inside emulated environment with functionality from [uaeexe.cpp](https://github.com/FrodeSolheim/fs-uae/blob/master/src/uaeexe.cpp). However I cannot find any documentation on how to use it.

Ideally, use scenario should be simply to launch run `uae_rcli` program inside emulated environment and run gcc testsuite under MacOSX / Linux. Of course DejaGNU must be properly configured to allow it to run commands under AmigaOS, but I know how to do it.

So the question is - how to invoke a command remotely? I assume a directory with test binaries will be shared between host and AmigaOS. Perhaps @tonioni could also help to answer this question?

**Comment by cahirwpz** [comment]
I've found remnants of support for remote command invocation in [e-uae/src/gui-muirexx/ami-rexx.c](https://github.com/keirf/e-uae/blob/master/src/gui-muirexx/ami-rexx.c#L399).

@cnvogelg Would it be possible to extend lua shell to call `uaeexe` function?

**Comment by tonioni** [comment]
Do you "only" need normal remote cli/shell (similar to newshell aux: with serial cable but via TCP socket) or something more complex?

**Comment by cahirwpz** [comment]
I expect that DejaGNU requires to capture exit code and likely stdout and stderr to run gcc testsuite correctly. I guess that above requirements could be dropped as long as wrapper script could provide the data in the other way.

**Comment by cnvogelg** [comment]
I have a similar use case when testing native binaries on vamos against real Amiga OS: I use FS-UAE and boot it from a shared folder with a customized startup sequence: run the test binary, redirect any output, save exit code and quit FS-UAE with UAE's internal emu quit trap (I hacked a tiny cli command to do the latter). 

This is all wrapped up in a small shell script and gives you a ```run-in-fsuae binary```experience on your shell.

Although this approach is quite "heavy" (It launches FS-UAE and the OS for a single test run) it works as expected and gives reproducible results. The only annoying thing is that the emulator window pops up for a second (that's why I requested #91)

**Comment by cahirwpz** [comment]
For the time being `make check-gcc` prints out:
```
# of expected passes            10090
# of unexpected failures        4914
# of unexpected successes       2
# of expected failures          78
# of unresolved testcases       152
# of unsupported tests          58
```
@cnvogelg I cannot imagine running ~5k tests using your solution. Launching UAE & AmigaOS for each test would create enormous overhead. While corectness and robustness is important I cannot ignore efficiency in my case.

**Comment by cnvogelg** [comment]
Regarding uaeexe: You need to run [uae_rcli](https://github.com/keirf/e-uae/blob/master/amiga/source/uae_rcli.c) inside UAE, e.g. from User-Startup. It uses the trap from useexe.cpp and waits for commands to be injected. The [uaeexe](https://github.com/FrodeSolheim/fs-uae/blob/master/src/uaeexe.cpp#L49) call then injects these commands. What's missing is a FS-UAE binding to make this feature available.
As you mentioned the lua extension could be a way to add it. Shouldn't be that hard to add.

**Comment by cnvogelg** [comment]
Done: [added lua uae.exe command](https://github.com/cnvogelg/fs-uae/commit/126f08f7a2d02d43fea9c3652ec58e471a3ddc46)
