### ISSUE TITLE
Confused graphical layers in Battle Squadron

### ISSUE THREAD

**Issue by Silicomancer** [FrodeSolheim/fs-uae#113]
I tried to run the old A500 game Battle Squadron using FS-UAE stable 2.6.2 on a Kubuntu PC.

The game works well with one exception: One of the background layers is above the space ships and hides them (but it should be under the ships). This seems to be a bug since I tried the same game image on a different Kubuntu PC and it works flawless there.

Please tell me if I can provide additional information to help fix that nasty bug.

**Comment by FrodeSolheim** [comment]
Hi, a screenshot of the problem would be useful, but more importantly, fs-uae.log.txt from both computers (remember to specify which one is the "working one"). See http://fs-uae.net/log-files-needed for more information about log files.

**Comment by Silicomancer** [comment]
Here is a screen shot where you can see the space ships under the grey background layer. Also it seems that the coloured stars are above the "M" nova missile icons.
Also I attached both the zipped Log folder.
This is done with the PC that once worked fine. I do not know what has changed but currently both systems suffer from the error. Probably some update broke the other system too. The last time it tested this was several weeks ago.

![shot](https://cloud.githubusercontent.com/assets/3684359/14833031/6ddca36c-0bfd-11e6-83c4-0bff6c0a7f79.png)
[Logs.zip](https://github.com/FrodeSolheim/fs-uae/files/237439/Logs.zip)

**Comment by Silicomancer** [comment]
Is the data sufficient for analysis?

**Comment by FrodeSolheim** [comment]
Hi, I've checked the logs, and I see that you are using the internal kickstart replacement. You should use the original A500 kickstart ROM for best game compatibility.

**Comment by FrodeSolheim** [comment]
Closing, please re-open if using the original A500 kickstart does not fix the problem.

**Comment by Silicomancer** [comment]
You are totally right. Both installations lost the imported ROMs. I bought and imported them long time ago. I have no idea why the imports got lost... but that also explains why it worked at the second PC and stopped working recently. Strange. I had no idea there is such thing as a kickstart replacement... otherwise I would have checked the ROM import first. I assumed the imported ROM are still in use. Sorry for bothering you. Many thanks for your help!

**Comment by rofl0r** [comment]
but then... shouldnt the integrated ROM be fixed to be as compatible as possible ?

**Comment by FrodeSolheim** [comment]
@rofl0r That would be nice of course, but not an FS-UAE issue!

**Comment by rofl0r** [comment]
that indeed is true. is @tonioni following this issue tracker

**Comment by FrodeSolheim** [comment]
The internal kickstart is the m68k version of the AROS kickstart.

**Comment by rofl0r** [comment]
yes, but isnt toni its author ?

**Comment by tonioni** [comment]
Fixed in AROS SVN. (But technically it is game bug, not setting BPLCON2)

**Comment by rofl0r** [comment]
very nice, thanks a lot!
