### ISSUE TITLE
Dead URL in blob/master/INSTALL

### ISSUE THREAD

**Issue by Enverex** [FrodeSolheim/fs-uae#116]
The "compiling fs-uae" section contains a link to http://fengestad.no/fs-uae/compiling which apparently contains the compilation instructions, but the link is dead.

**Comment by Enverex** [comment]
Created a simple pull with the correction here - https://github.com/FrodeSolheim/fs-uae/pull/117

**Comment by FrodeSolheim** [comment]
Thanks, merged :)
