### ISSUE TITLE
Incorrect Example on "Configuration Options" Documentation Page

### ISSUE THREAD

**Issue by Enverex** [FrodeSolheim/fs-uae#118]
The configuration options page (https://fs-uae.net/options) lists the following example for amiga_model:

`Example: amiga_model = 1200/020`

But that won't actually work, the models listed below in the documentation are correct (e.g. "A1200/020"). Basically the "A" is missing from the example.

**Comment by FrodeSolheim** [comment]
Fixed, thanks :)
