### ISSUE TITLE
Pulse audio?

### ISSUE THREAD

**Issue by gerroon** [FrodeSolheim/fs-uae#122]
Hi

I am not sure how to describe this issue but I will try anyways.

I have multiple sound cards on my Debian so I use Pulseaudio's interface to select the right soundcard per app. 

Every app on my system is able to play on Pulseserver's external sink except Fs-uae. I cant cahnge the default sound server from the built in to the external sound card inside the pulseaudio control for Fs-Uae. And it is the only app that is not accepting the external audio.

The weird thing is that this was not an issue in the past because I was able to play audio with Fs-uae with my external audio card however this changed. I am not sure in which version this change happened.

thanks

**Comment by FrodeSolheim** [comment]
Hi, I'm not not sure why this happens to you. FS-UAE does not use PulseAudio directly btw, it uses OpenAL. You can create a config file (~/.alsoftrc) to set OpenAL Soft options. For example, you can for specific audio backends.

For example, try adding **one** of these lines to ~/.alsoftrc and see if it helps:
drivers=pulse
drivers=alsa

**Comment by FrodeSolheim** [comment]
Closing due to lack of information, and also because the audio system has been replaced for the upcoming 4.0 version. But do please report a new bug if there are issues with 4.0 when it is released.
