### ISSUE TITLE
XZ image compression support

### ISSUE THREAD

**Issue by fturco** [FrodeSolheim/fs-uae#124]
Let me suggest adding XZ image compression support to FS-UAE. This would allow saving some space as opposed to using Zip compression.

As a test I tried compressing 26,330 ADF images with both the zip and xz algorithms:
- Uncompressed total size: 22,659 MiB
- Zip-compressed total size: 13,038 MiB
- Xz-compressed total size: 11,596 MiB

So I was able to save 1,442 MiB of space (-11%). That's not a lot but still a significant amount in my opinion.

In my test I used xz default options. With options `-9e` one may obtain even better results, but I have not tried yet.

What do you think?

**Comment by fturco** [comment]
Options `-9e` don't achieve better compression: 11594 MiB instead of 11596 MiB (just 2MiB saved over 26,330 ADF images!).

**Comment by FrodeSolheim** [comment]
Are we talking about FS-UAE Launcher and online game database support? It is probably trivial to add support for .adf.xz... (one ADF image compressed per .xz file) in FS-UAE Launcher.

**Comment by FrodeSolheim** [comment]
(I mean that .tar.xz (or .7z) is more work and less likely to be done...)

**Comment by fturco** [comment]
Yes, I'm talking about FS-UAE Launcher. Support for .adf.xz would be fine.

**Comment by FrodeSolheim** [comment]
Support for .xz files in FS-UAE Lancher has been added to version 2.9.11dev, out now :)
