### ISSUE TITLE
Importing/sorting recognized image files only

### ISSUE THREAD

**Issue by fturco** [FrodeSolheim/fs-uae#126]
I downloaded thousands of Amiga games from the Internet Archive and I'd like to add them to FS-UAE. In particular I'd like to only import images whose checksum is known to the Open Amiga Game Database, and discard the rest as untrustworthy. I'm not sure such feature should be implemented in FS-UAE or FS-UAE Launcher.

**Comment by FrodeSolheim** [comment]
It should definitively not be added to FS-UAE itself, as FS-UAE does not even know about the database.

However, I don't have any current plans to add such a feature to FS-UAE Launcher. It would also be somewhat unfortunate to discard unrecognised disks, as new disks are still being added to the database.

(It is possible for someone else to create such a utility though, by using the database files downloaded by FS-UAE Launcher).
