### ISSUE TITLE
Consider testing for, and adding, -no-pie linker flag

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#128]
Adding -no-pie should prevent compiler defaults from creating a position-independent executable, which could mess with FS-UAE's ability to use JIT (if program/data sections are moved above 0xffffffff).

**Comment by Enverex** [comment]
Let me know if you'd like me to test anything regarding this.

**Comment by FrodeSolheim** [comment]
The latest version in GIT enables use of "-no-pie" automatically. If you do compile from GIT, please give it a try :)

**Comment by FrodeSolheim** [comment]
Implemented in https://github.com/FrodeSolheim/fs-uae/commit/55e3f2129947efc8b6ea7f47cf00a50b519e8f6e, https://github.com/FrodeSolheim/fs-uae/commit/098f9337fb7499c116fbbbbc88db5b663ac4d82c
