### ISSUE TITLE
Restoring from fullscreen to windowed on Wayland does not resize content

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#130]
(On Fedora 24, Wayland session)

Looks like an SDL2 problem (could be fixed in newer versions) or a Wayland issue (could also be fixed in newer versions), because it does not look like FS-UAE gets either a resize event nor a restore event when returning from fullscreen.

**Comment by digitalstreamio** [comment]
I will retest w/ F25 beta when that comes out and update the issue with my findings.

**Comment by FrodeSolheim** [comment]
@digitalstreamio How does it work with Fedora 25? :)

**Comment by digitalstreamio** [comment]
There seems to be a regression in F25 that prevents me from retesting this issue. I filed a bug with RH folks as SDL2 no longer seems to like Wayland. 

https://bugzilla.redhat.com/show_bug.cgi?id=1390233

I will try to update this issue as soon as I figure out how to get around SDL2 regression.

**Comment by digitalstreamio** [comment]
I finally got tired on waiting for an update from RH boys and compiled my own build of SDL2 that enables Wayland backend. 

FS-UAE works like a charm with SDL_BACKEND=wayland. Switching to fullscreen and back to windowed mode works great! 

Previously, I had also ran into an issue with cursor getting locked out of an area of the screen after switching between fullscreen/windowed mode. That no longer applies so looks like windowing/input support is solid.

The downside is that other Fedora users will need to wait a bit longer until SDL2 build is fixed but at least that is a different bug tracker. :)

**Comment by digitalstreamio** [comment]
It appears SDL2-2.0.5-2.fc25.x86_64.rpm package in F25 repo also seems to work. So all good on all ends now. Thanks

**Comment by digitalstreamio** [comment]
Argh, I think its getting late and I'm getting tired. 

I tested with SDL_BACKEND=wayland which is wrong. It should have been SDL_VIDEODRIVER=wayland. 

Anyways, on Wayland session through XWayland FS-UAE behaves great.

However, I still need to wait for an update to SDL2 to test FS-UAE Wayland client on Wayland server.

**Comment by digitalstreamio** [comment]
The good news is I was able to get SDL2 Wayland backend up and running. It appears to be a regression in gnome-shell/gdm/kernel KMS mode initialization.

https://bugzilla.redhat.com/show_bug.cgi?id=1403512

The less good news is that resizing fs-uae window to full-screen doesn't work properly. The window goes full-screen, but the scaling is incorrect and I can only see portion of the workbench. Restoring from full-screen to windowed also doesn't seem to set scaling properly.

**Comment by digitalstreamio** [comment]
This appears to be an upstream issue. I filed a bug with Gnome wayland folks.

https://bugzilla.redhat.com/show_bug.cgi?id=1403968

**Comment by FrodeSolheim** [comment]
Thanks for testing and following up on this :+1:
