### ISSUE TITLE
No f12 on chromebook pls add mapping action

### ISSUE THREAD

**Issue by Phill23** [FrodeSolheim/fs-uae#132]
I searched a lot but found no answer, without f12 I cannot access the menu.
alt + z,b,p,f,,,. etc. works fine but for some actions I need the menu.

**Comment by Phill23** [comment]
I used xdotool to map F12 to Ctrl+Alt+m but it would be nice to be able to do this in the config.

**Comment by jackokring** [comment]
I assume only idiots would VirtualBox an instance so suggest right control as assignment.
