### ISSUE TITLE
Mouse pointer under OSX/Linux

### ISSUE THREAD

**Issue by arti040** [FrodeSolheim/fs-uae#133]
Maybe it should not be in issues, but I got one, simple, general question ;-) - why mouse pointer behaviour and focusing FS-UAE window under MacOSX/Linux is literally so fucked up? Two pointers at once (host OS/Amiga), emulator window constantly loosing focus and/or mouse coordinates causing AmigaOS pointer locking and other, strange behaviours. Why it can just work so flawlessly like in WinUAE does?

**Comment by FrodeSolheim** [comment]
Hi, I have never of such issues. You will get two pointers if you release the mouse grab (Alt+G or middle mouse button), but when using/controlling the Amiga then FS-UAE should grab the mouse and the host cursor should be hidden.

**Comment by arti040** [comment]
Sometime it does, sometimes does not and then there are two of them (on OSX Sierra at least) or everything locks, but that's the less inconvenient part. Losing window focus when moving pointer around Workbench screen is far more painful and annoying. I can record you a video, if you want.

**Comment by arti040** [comment]
Yep. It happens only in window mode, because in F-S mouse pointer has no where to "escape" (it's a lot of easier to show it than to explain it, haha). Also, in F-S mode there is only one (Amiga) pointer so all is OK.

PS: I've checked the latest version of FS-UAE on my Linux machine and there is only one (Amiga) pointer too but I can't release it back the host just by moving it outside the window (it's locked inside Amiga window). I need to hit f12+g first.

**Comment by FrodeSolheim** [comment]
Yes, the pointer is supposed to be locked :)

Hmm, have you by any chance disabled the options "Grab Input on Click" and/or "Grab Input on FS-UAE Startup" on your OS X-installation of FS-UAE?

**Comment by arti040** [comment]
If so, only by accident. Have no idea. Will check it at home.

**Comment by FrodeSolheim** [comment]
Closing due to lack of updated information.
