### ISSUE TITLE
[Question] Images only get downloaded when the game is manually clicked.

### ISSUE THREAD

**Issue by shad00m** [FrodeSolheim/fs-uae#134]
Images/Covers for the game only get downloaded when the game has been clicked in FS-UAE.
This has been probably implemented to not stress the oagd servers too much but is there a way to let it download (threaded or slowly if it stresses the server too much) all the Images/Covers for games added in the database?

**Comment by FrodeSolheim** [comment]
There's no functionality for background download in FS-UAE Launcher (FS-UAE Arcade pre-downloads media for the few "surrounding games").

But you can download all images/covers in one go from https://openretro.org/download (Images_Amiga.zip) :)

**Comment by shad00m** [comment]
Oh! Thank you very much for that link :)
