### ISSUE TITLE
Problem with AGA after last commit

### ISSUE THREAD

**Issue by escalade** [FrodeSolheim/fs-uae#136]
Looks like model=a1200 breaks with commit https://github.com/FrodeSolheim/fs-uae/commit/f67746941fae0448c0e8558a7952dab444766899, there's only a black screen. Rolling back to the previous commit works fine.

**Comment by Enverex** [comment]
Confirmed, just getting a black screen with CD32 (but no errors, notices or warnings).

**Comment by FrodeSolheim** [comment]
Thanks for the bugreports, fixed in 1e5562228258d9c1d18eed03fcbe0dad4f76ccbf :)
