### ISSUE TITLE
Support for building on Raspberry Pi

### ISSUE THREAD

**Issue by midwan** [FrodeSolheim/fs-uae#138]
Running "configure" currently goes through configuring several items but stops with:

configure: error:  --enable-jit was given, but arch is not supported

What would be needed to add support for the RPI platform? I'm referring to the stock Raspbian installation on a RPI3 (armv8)

**Comment by solskogen** [comment]
Rasbian on RPi3 is not 64bit.

**Comment by midwan** [comment]
Ah, I wasn't aware this is 64-bit only. Is that a hard requirement?

**Comment by solskogen** [comment]
As far as I know FS-UAE only supports JIT on x86/x86-64

**Comment by escalade** [comment]
There's a [libretro fork](https://github.com/repojohnray/libretro-fsuae) that runs on the RPi (without JIT). Development seems to have stagnated though.

**Comment by midwan** [comment]
Thanks for the link.

**Comment by FrodeSolheim** [comment]
@midwan It does build on the Raspberry, but you to run configure with:

    ./configure --disable-jit

FS-UAE is not 64-bit only. It builds and runs on a variety of operating systems and architectures. As noted by @solskogen, the JIT compiler is only available on x86 and x86-64.

**Comment by midwan** [comment]
@FrodeSolheim thanks, I assumed that was the case (but wasn't sure if it was tested).

There are some efforts for having JIT running on ARM, for example the Aranym project (https://github.com/bobek/aranym-debian). Perhaps you'd consider looking into that?

We use a version of JIT based on Aranym on the uae4arm-rpi (https://github.com/midwan/uae4arm-rpi) project also, though it's not complete and there are other problems with that emulator (hence my investigation if it's worth continuing working on that or maybe invest in fs-uae instead).

**Comment by FrodeSolheim** [comment]
Yes, in fact, 90% of the x86-64 JIT support comes from the Aranym project. Right now, the FS-UAE/WinUAE and Aranym JIT compilers are very close to each other, so ARM support is definitively possible, but some UAE-specific code must be written (not trivial).

But please also note that FS-UAE performance on PI3 is currently really slow, not only because of the demands of the Amiga emulation, but the video renderer via OpenGL is itself also slow on the PI3.

**Comment by solskogen** [comment]
The uae4arm-rpi seems to have a decent JIT for ARM.

**Comment by escalade** [comment]
@FrodeSolheim 

I haven't tested pure fs-uae on the rpi but performance was OK with the libretro port and accuracy=0.

**Comment by FrodeSolheim** [comment]
Closing this issue though, since FS-UAE does compile on Raspberry PI :)
