### ISSUE TITLE
configure does not check for zip

### ISSUE THREAD

**Issue by solskogen** [FrodeSolheim/fs-uae#139]
If the zip command is not available, the build will fails like this:

/bin/sh: -r: command not found
make[2]: *** [Makefile:5112: fs-uae.dat] Error 127
make[2]: Leaving directory '/home/solskogen/source/fs-uae'
make[1]: *** [Makefile:4311: all-recursive] Error 1
make[1]: Leaving directory '/home/solskogen/source/fs-uae'
make: *** [Makefile:2382: all] Error 2

the configure script should check if zip is available, and fail if it is not.

**Comment by rofl0r** [comment]
> the configure script should check if zip is available, and fail if it is not.

or maybe even better, use tar instead for whatever it wants to do...

**Comment by solskogen** [comment]
That's usually not available on Windows.

**Comment by FrodeSolheim** [comment]
Fixed in https://github.com/FrodeSolheim/fs-uae/commit/84498978372e27934626608b064aaac6eee63988 :)
