### ISSUE TITLE
RMB menus disappear in Warp mode

### ISSUE THREAD

**Issue by MetinSeven** [FrodeSolheim/fs-uae#149]
Hi,

When I've activated Warp mode in FS-UAE for MacOS, right mouse button drop-down menus disappear shortly after they appear, making them unusable. Right now I have to disable Warp mode each time I want to use a right mouse button drop-down menu in Deluxe Paint or anywhere else.

I'm using a Wacom Cintiq with the right mouse button assigned to a side-button of the pen. Don't know if that might cause the problem? The Wacom drivers just emulate the right mouse button, and it works everywhere.

Thanks in advance for fixing this, and keep up the good work!

Best regards,

Metin

**Comment by FrodeSolheim** [comment]
You're not meant to use the emulator in warp mode, it's just meant for fast-forwarding through loading, etc. So I don't really consider it a bug. Not sure why you are using warp mode. Maybe just use an A4000 model instead of you want to run the emulation as fast as possible, normally?

**Comment by MetinSeven** [comment]
Thanks for your reply, Frode. I already use an A4000/040, but Warp Mode makes live drawing pleasantly smooth and fast when using a drawing tablet as input.
