### ISSUE TITLE
Any .lha archive doesn't start with fs-uae-lancher WHDLoad support

### ISSUE THREAD

**Issue by i30817** [FrodeSolheim/fs-uae#150]
Version 2.9.4dev from the dev ppa.

Maybe i'm doing something wrong. I configured the kickstarts ok, and then i had some WHDLoad games to try to boot. I loaded it in as a hd, first on the list. The launcher filed in the WHDLoad arguments automatically:
Apocalypse.slave PRELOAD CUSTOM1=1 

a error message box appeared:
"Amiga Launch Task failed with Exception:
'Did not find the specified WHDLoad slave. Check the WHDLoad arguments'

See log file for details."

cmd line doesn't say much:

> LaunchHandler.prepare_hard_drives
>  -- Preparando os discos rígidos... --
> zipped hard drive /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha
> ImplicitConfigHandler.do_update
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha
> unpack /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha to /tmp/fs-uae-4opi8lzz/DH0
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha
> <fsgs.Archive.Archive object at 0x7fee48086710>
> get_handler /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha
> <fsgs.Archive.LhaHandler object at 0x7fee48086c18>
> <fsgs.Archive.LhaHandler object at 0x7fee48086c18>
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse.info
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse.info
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse.info
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fApocalypse.info
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fApocalypse.info
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fApocalypse.info
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fApocalypse.Slave
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fApocalypse.Slave
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fApocalypse.Slave
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fDisk.1
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fDisk.1
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fDisk.1
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fDisk.2
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fDisk.2
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fDisk.2
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fDisk.3
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fDisk.3
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fDisk.3
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fManual
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fManual
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fManual
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fManual.info
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fManual.info
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fManual.info
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fReadMe
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fReadMe
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fReadMe
> /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fReadMe.info
> out path /tmp/fs-uae-4opi8lzz/DH0/Apocalypse%5fReadMe.info
> split_path /media/i30817/backup/Documents/Games/Amiga/whdload/Apocalypse_v1.0_1813.lha#/Apocalypse%5fReadMe.info
> copy_hd_files, dest_dir =  /tmp/fs-uae-4opi8lzz/DH0
> opening database /media/i30817/Huggin/Documents/FS-UAE/Data/Databases/Files.sqlite
> opening database /media/i30817/Huggin/Documents/FS-UAE/Data/Databases/Locker.sqlite
> WARNING: did not find SetPatch 39.6
> [WHDLOAD] LaunchHandler.copy_whdload_files
>  -- Preparando WHDLoad... --
> [WHDLOAD] copy_whdload_files, dest_dir =  /tmp/fs-uae-4opi8lzz/DH0
> ImplicitConfigHandler.do_update
> <Task "Amiga Launch Task"> failed 'Did not find the specified WHDLoad slave. Check the WHDLoad arguments'
> Traceback (most recent call last):
>   File "/usr/share/fs-uae-launcher/fsbc/task.py", line 59, in __run
>     self.run()
>   File "/usr/share/fs-uae-launcher/launcher/launcherapp.py", line 549, in run
>     self.launch_handler.run_sequence()
>   File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 118, in run_sequence
>     self.prepare()
>   File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 105, in prepare
>     self.copy_hd_files()
>   File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 687, in copy_hd_files
>     self.copy_whdload_files(dest_dir, s_dir)
>   File "/usr/share/fs-uae-launcher/fsgs/amiga/LaunchHandler.py", line 735, in copy_whdload_files
>     "Did not find the specified WHDLoad slave. "
> Exception: Did not find the specified WHDLoad slave. Check the WHDLoad arguments
> BaseDatabase.__del__
> BaseDatabase.__del__

Looking at the tmp dir on ' /tmp/fs-uae-4opi8lzz/':

`/tmp/fs-uae-4opi8lzz$ tree
.
├── DH0
│   ├── Apocalypse%5fApocalypse.info
│   ├── Apocalypse%5fApocalypse.Slave
│   ├── Apocalypse%5fDisk.1
│   ├── Apocalypse%5fDisk.2
│   ├── Apocalypse%5fDisk.3
│   ├── Apocalypse%5fManual
│   ├── Apocalypse%5fManual.info
│   ├── Apocalypse%5fReadMe
│   ├── Apocalypse%5fReadMe.info
│   ├── Apocalypse.info
│   ├── C
│   ├── Devs
│   ├── Fonts
│   ├── Libs
│   └── S
├── Kickstart v1.3 r34.5 (1987)(Commodore)(A500-A1000-A2000-CDTV)[!].rom
└── Save Disk.adf

6 directories, 12 files
`

Not sure if the subdirectory structure is supposed to be flattened like that (the '%5' on the filenames is i believe the directory separator encoded into the filename, as the prefix is the subdir name).
`uname -a
Linux AIVAS 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by i30817** [comment]
BTW isn't the whdload autodetect supposed to configure the machine too, isn't that info in the database?

**Comment by FrodeSolheim** [comment]
Looks like a "corrupt archive" (as in weird filenames in the archive). %5f should have been a slash (directory separator), as you say.

Yes, the launcher can autodetect the game and configure a suitable model. But the online game database is not utilized when you simply load the archive with the hard drive selector. Instead, you let the Launcher scan the game archive(s), and the games will (if recognized) appear in the configuration list.

**Comment by i30817** [comment]
I don't think it's a simple 'corrupt data' problem. For example, if i download straight off from whdload, monkey island for example:
http://www.whdload.de/games/MonkeyIsland2.lha

Same thing is happening here (it doesn't autodetect this version, but it's MonkeyIsland2.Slave).

I believe it must be some sort of encoding problem. I'd appreciate if you could test the link in this post and see if it works fine for you (as i suspect).

**Comment by FrodeSolheim** [comment]
http://www.whdload.de/games/MonkeyIsland2.lha is not an installed game which can be run. This is merely a game *installer* which can be used to install the WHDLoad version of Monkey Island 2 (manually) when provided with the original game media. These archives cannot be used with the game database.

**Comment by i30817** [comment]
Ughh, never mind, i was missing the whole process by not performing log-in. I had no idea it was required for the config.

**Comment by i30817** [comment]
BTW, @FrodeSolheim, although i solved this, i'm very unsure if there isn't a bug here. Needing to login to the database and scan the games to be able to boot a WHDload archive limits the usability. Is this really a hard requirement in order not to corrupt extraction?

**Comment by FrodeSolheim** [comment]
Needing to log in is not a requirement to use WHDLoad game archives, only to get the configs from the database. As I indicated earlier, it looks like that archive you were using was invalid (i.e. missing proper directory separators). When using the online game database, the Launcher can ignore the file names inside the archives, since it gets the correct file hierarchy from the database, finds files based on checksums, and creates the correct file structure automatically.

When you (just) provide the launcher with an archive, it uses the file structure from the archive, so if the structure in the archive is messed up (as with the %5f "separators"), it will not work. Give it a proper archived WHDLoad game installation, and it should be able to boot it!

(If you think the archive is not messed up, you can try to open it in another archiving software and see if the folder structure is intact).
