### ISSUE TITLE
Some games don't remap cursor keys and joystick to host keypad?

### ISSUE THREAD

**Issue by i30817** [FrodeSolheim/fs-uae#151]
I don't currently have a gamepad, joystick or working keyboard cursor keys. I tried to put this on advanced settings:

> keyboard_key_kp1 = action_key_cursor_left
> keyboard_key_kp2 = action_key_cursor_down
> keyboard_key_kp3 = action_key_cursor_right
> keyboard_key_kp5 = action_key_cursor_up
> keyboard_key_kp7 = action_dpad_left
> keyboard_key_kp8 = action_dpad_down
> keyboard_key_kp9 = action_dpad_right
> keyboard_key_kp_divide = action_dpad_up

When i tried '1000c Turbo' it refused to recognize the keypad host keys as the equivalent. In fact, it still used the host cursor keys (one of them 'right' still works here).

Another strange case i saw was '4x4 Off-Road Racing'. In there the 'action_key_cursor' remaps work but the 'action_dpad' ones have strange results. Namely 'keyboard_key_kp8' seems to go 'up' instead of down, 'keyboard_key_kp7', 'keyboard_key_kp9' and 'keyboard_key_kp_divide' don't seem to do anything. This game also allowed the host 'right' to work even if the action was configured to another key above (this makes sense in retrospect if the remaps are a alternative, not a substitution). 

These two games are auto-configured from the WHDload support as '1200' (1000cc Turbo) and '600' (4x4 Off-Road Racing) so it shouldn't just be the different emulated keyboard not having keypad.

Also i'm using a portuguese keyboard, so maybe that influences the semi-random brokenness. I actually have similar problems in retroarch where the upper row (kp7,kp8,kp9,kp_divide) also have problems mapping to host on some of the virtual keys (second stick, switched axis, switching remaps manually doesn't work).

edit: i actually think this is not working at all now. Or if it's working it's not replacing the 'joystick events' but the keyboard controls if any. That should explain why some games bug out (they recognize that a joystick is connected and prefer it). I need a way to override the fs-uae-loader joystick assigment to keyboard and which action events are the right ones to replace and to make sure it doesn't get overwritten.

**Comment by i30817** [comment]
Never mind, found a alternative by reading the code. Not sure if the cd32 keys are correct, but the joystick mapping is:

> # This example config file, if dropped into FS-UAE/Data/Devs/Keyboards,
> # will override the keybindings used for keyboard joystick emulation for
> # Amiga only, and leave keybindings for other systems intact (by including
> # default_keyboard).
> 
> [device]
> name = Keyboard
> type = keyboard
> attached = 1
> 
> [default]
> include = default_keyboard
> 
> [amiga]
> key_kp1 = left
> key_kp3 = right
> key_kp5 = up
> key_kp2 = down
> key_lctrl = 1
> key_lshift = 2
> key_lalt = 3
> red = z
> blue = x
> yellow = s
> green = a
> forward = end
> rewind = pgdown
> play = home
> autofire = rctrl
> toggle_autofire = pgup

**Comment by FrodeSolheim** [comment]
The [cd32] section is incorrect, yes. For reference, the default is:

    [cd32]
    key_left = left
    key_right = right
    key_up = up
    key_down = down
    key_rctrl = red
    key_ralt = red
    key_c = red
    key_x = blue
    key_d = green
    key_s = yellow
    key_return = play
    key_z = rewind
    key_a = forward
