### ISSUE TITLE
Navigating the menus with defective keyboard

### ISSUE THREAD

**Issue by i30817** [FrodeSolheim/fs-uae#152]
For the same reason as #151, i can't navigate the menu after pressing F12, even after my workaround in post 2 of that issue. I'd like to request the mouse be a input method there, or that the same keys as the emu movement are used.

**Comment by i30817** [comment]
Thinking about this, overriding the keyconfig like in the 2nd post of #151 with a 'menu' section in addition to the 'amiga' and 'cd32' would be enough too.

**Comment by FrodeSolheim** [comment]
Yes, you can add a [menu] section to the keyboard config file. Here is the default [menu] section:

    [menu]
    key_left = left
    key_right = right
    key_up = up
    key_down = down
    key_return = primary
    key_space = secondary
    key_backspace = back
    key_pageup = skip_left
    key_pagedown = skip_right
    key_escape = escape

**Comment by i30817** [comment]
Perfect, thanks. Something to be added to the wiki i guess.
