### ISSUE TITLE
Fatal interaction with web browser on Linux 4.11

### ISSUE THREAD

**Issue by tac1ica** [FrodeSolheim/fs-uae#160]
When running on Linux with a 4.11 kernel, fs-uae kills whatever web browser (tested with Chromium and Firefox) is running. The mouse pointer in the emulation becomes jerky (one position update every 0.5 secs or so), then at some point the web browser running on Linux stops responding and needs to be forcibly killed to recover normal operation.

This is not a low memory problem: there are ~6GB something RAM free (of 8GB total installed on the machine) when this happens, swap isn't being consumed.

The box where this is happening is an Intel Quad Core 2 Quad with 8GB of RAM running a current Void Linux Mate based on glibc, which should ensure maximum compatibility.

The same box can run fs-uae just fine (including fs-launcher, which I couldn't manage to run on Void) with Linux Mint 18.1 Serena XFCE, which is based on kernel 4.4. The behaviour can't be reproduced on that config.

### Steps to reproduce the problem

1. Navigate to https://repo.voidlinux.eu/live/current/ and download Void Linux. The live image used here is https://repo.voidlinux.eu/live/current/void-live-x86_64-20170220-mate.iso

2. Install the image and then reboot to start the new OS.

3. From within Void Linux, open a console and enter

> $ sudo xbps-install -Suv

4. Repeat the command again until no more updates are available. By now you should have kernel 4.11.8 installed, which is flagged as STABLE in https://www.kernel.org

5. Reboot to enable the new kernel.

6. Install the latest stable fs-uae. Since there isn't a current build available on the Void repos, I'm using the regular archive <https://fs-uae.net/stable/2.8.3/fs-uae_2.8.3_linux_x86-64.tar.xz> with fs-uae only, and run fs-uae direct from the console.

7. Open Firefox as you normally would, open a couple of tabs.

8. Run fs-uae and start the emulation.

9. Switch to Firefox and keep switching between tabs a few times.

10. Switch to fs-uae again.

By now you should notice the emulation has become unusable and you have a jerky mouse pointer on the emulated Amiga, otherwise switch between the browser and fs-uae a few more times until it happens.

At some point the browser dies, the window stops responding (you can't even move it around) and the only thing you can do is kill it from the task manager. After that's done, fs-uae may or may not recover normal behavior after a while.

Even if you exit fs-uae instead of the web browser, the browser never recovers and must be killed anyway. This anomaly can also be reproduced with Chromium.

While this is going on, **top** reports fs-uae is consuming >100% CPU time, I've seen it  reach 102%. Under normal operation it is 90 something %, 100% maximum.

The stock Void Linux image comes with kernel 4.9.11, and the problem was reproducable there too. I upgraded to 4.11.8 just today and was expecting a change for the better, but it didn't happen.

This looks to me like an unfortunate kernel/X.org/AMD driver/fs-uae interaction. I'm attaching the fs-uae logs and config, and the output from inxi describing this system. We can meet on IRC if you want live testing.

[Default.fs-uae.txt](https://github.com/FrodeSolheim/fs-uae/files/1115216/Default.fs-uae.txt)
[debug.uae.txt](https://github.com/FrodeSolheim/fs-uae/files/1115218/debug.uae.txt)
[fs-uae.log.txt](https://github.com/FrodeSolheim/fs-uae/files/1115219/fs-uae.log.txt)
[inxi_output.txt](https://github.com/FrodeSolheim/fs-uae/files/1115220/inxi_output.txt)

**Comment by FrodeSolheim** [comment]
I'm assuming for now that this wasn't an FS-UAE bug. Please re-open if this still is a problem and something indicates that FS-UAE is the culprit.
