### ISSUE TITLE
Deactivation of emulator shortcuts

### ISSUE THREAD

**Issue by gryf** [FrodeSolheim/fs-uae#161]
I found it annoying, that there are some keys hard coded for doing certain actions, like leftalt+f4 for closing emulator, leftalt+s is mapped for making screenshot, leftalt+w is for wrap mode, leftalt+tab for switching emulator window etc. Left alt seems like have the most of the function as a F12 key.
From games perspective it might be a minor issue, however it is annoying in emulated AmigaOS - mapping keys under those already taken via emulator is impossible. Is it possible to have a switch (i.e. F12+K for example) to turn off all alt related mappings and expose those to the underlying AmigaOS? Or maybe configuration option would be easier to implement…

**Comment by FrodeSolheim** [comment]
Both exists. It is F12+K... There is also an option (full_keyboard).

**Comment by gryf** [comment]
Awesome! But the [docs](https://fs-uae.net/keyboard-shortcuts) are not up to date :(

**Comment by FrodeSolheim** [comment]
It's mentioned in the new docs :)

**Comment by FrodeSolheim** [comment]
https://fs-uae.net/docs/keyboard

**Comment by gryf** [comment]
I'm wondering if it's not crazy idea to put some warning box in outdated documentation pages with link to the index of great, new docs? :D
