### ISSUE TITLE
Add macOS native full screen support

### ISSUE THREAD

**Issue by gklka** [FrodeSolheim/fs-uae#166]
Current full screen options are very hard to use in multitasking environment. I think a native full screen on macOS (which renders the app as a space in the Mission Control) would fit better.

**Comment by borb** [comment]
`SDL_VIDEO_MAC_FULLSCREEN_SPACES = 1`

From https://fs-uae.net/docs/faq

**Comment by FrodeSolheim** [comment]
Nothing to do here :)
