### ISSUE TITLE
Automatic language detection picks French for English Canadian macOS 10.13.3

### ISSUE THREAD

**Issue by barbeque** [FrodeSolheim/fs-uae#169]
# System
 * English Canadian macOS 10.13.3 install on a MacBook Pro.
 * Region set to Canada.
 * Preferred languages in Language & Region control panel: English (Canada) - primary, French (Canada), Deutsch, Chinese Simplified, Japanese, Spanish (this is the default setup for an English Canadian MacBook out of the box).
 * FS-UAE Launcher 2.8.3 from the FS-UAE Suite DMG, downloaded today.

# Reproduction Steps
 1. Open FS-UAE Launcher app.
 2. Make sure that language is set to "Automatic" in the settings (FS-UAE menu, top left)
 3. Start the emulator, all default Amiga settings (A500, AROS Kickstart, etc).
 4. Push Cmd-W ("Warp Mode")
 5. You will see a French translation of the string displayed on the OSD. Other features (blitter zoom) will also display the French translation.

# Expected behaviour
Since the currently selected language in macOS is English, the automatic language detection should default to English.

# Workaround
Forcibly setting the language in the Launcher settings to English means that strings appear in English.

# Theory
I am guessing this is because I am Canadian, so somehow it is assuming that I am also _French_ Canadian.

I can probably fix/debug this myself if someone were to point me to where the automatic language selection code is: I have not been able to locate it yet but have not done an intense search for it.
 
Logs attached. Note that the `fs-uae.log.txt` log says the locale is set to `en_CA`, but they also mention the French translation: `Mode Warp désactivé`. The Launcher log has a strange message about `gettext.NullTranslations`.
 
[fs-uae-arcade.log.txt](https://github.com/FrodeSolheim/fs-uae/files/1613715/fs-uae-arcade.log.txt)
[fs-uae-launcher.log.txt](https://github.com/FrodeSolheim/fs-uae/files/1613716/fs-uae-launcher.log.txt)
[fs-uae.log.txt](https://github.com/FrodeSolheim/fs-uae/files/1613717/fs-uae.log.txt)

**Comment by FrodeSolheim** [comment]
Thanks for a very thorough bug report! I will try to reproduce the problem.

**Comment by barbeque** [comment]
It looks like it was a bug in gettext: https://savannah.gnu.org/bugs/?49560

OpenSCAD had a similar problem on my computer as well: https://github.com/openscad/openscad/issues/1813

From reading this, my guess is that upgrading gettext and doing a new build of FS-UAE will fix this.

**Comment by FrodeSolheim** [comment]
Could you check if this is still an issue with the latest version 3.0.5?

**Comment by barbeque** [comment]
Just tested on 10.15.7 – looks like the bug is now fixed (says "WARP MODE ENABLED" before closing the window.) Thank you for taking care of this!

**Comment by FrodeSolheim** [comment]
Thanks for testing :)

PS: I think I've found a solution for #230 now as well, but it will require a new build with a custom patch to SDL (which I'll probably do)
