### ISSUE TITLE
WinUAE current relation

### ISSUE THREAD

**Issue by lyssdod** [FrodeSolheim/fs-uae#180]
Hi,
Are there any plans to merge WinUAE and fs-uae into single repository? Or at least unify emulation core? For example, make some "libuae", which can be reused  by both projects? I've raised similar question on WinUAE repo: https://github.com/tonioni/WinUAE/issues/142

**Comment by FrodeSolheim** [comment]
The code is, for most practical purposes "shared", as in mostly similar across the two repos. I try to ensure that the code is a similar as possible. Almost all code outside od-fs (FS-UAE) and od-win32 (WinUAE) is shared, and 99.9% identical. In addition, I try to use compile in code from od-win32 when possible. I don't see the repos being merged as such, but I will continue to send patches to WinUAE to unify code even more (when changes are needed for cross-platform compilation for example).
