### ISSUE TITLE
Can FS-UAE Launcher be added to the flatpak?

### ISSUE THREAD

**Issue by unholyeyebrows** [FrodeSolheim/fs-uae#185]
Hi

I'm keen to move to a flatpak based desktop and have installed FS-UAE from flathub. This only includes the emulator and not the launcher. Can the launcher either be added to this flatpak or provided as a separate package?

Many thanks in advance,

**Comment by digitalstreamio** [comment]
I just pushed an update to Flathub package that includes FS-UAE Launcher.  Pending build/ publishing workflow, it should show up on the website in the next day or two. Thanks

@FrodeSolheim Does Launcher require a specific version of the emulator? 

I'm currently using the latest dev version of launcher and the latest stable version of the emulator.

        url: https://github.com/FrodeSolheim/fs-uae-launcher
        branch: master
        commit: 233d2c65e6660ed9c9456a9b62e43e2cc7bc6d44

        url: https://github.com/FrodeSolheim/fs-uae
        branch: stable
        commit: 665457ec22500623f6374bef5bada6053057daa3

**Comment by unholyeyebrows** [comment]
Just to say many thanks for providing this update. Works well enough on my system.

**Comment by FrodeSolheim** [comment]
See https://github.com/FrodeSolheim/fs-uae/issues/172 for follow-up discussion :)

**Comment by gav-** [comment]
Just my flatpak ignorance, but could not find information on how to actually run fs-uae-launcher instead of fs-uae in flatpak. This issue is first hit in google, so adding this comment to save others some time:
`flatpak run --command=fs-uae-launcher net.fsuae.FS-UAE`

**Comment by Thornskade** [comment]
What happened to the launcher?
