### ISSUE TITLE
Feature request - API for remote installations inside emulator (ie. Ansible for Amiga)

### ISSUE THREAD

**Issue by davesade** [FrodeSolheim/fs-uae#188]
Idea is, that systems like ClassicWB, AmiSYS or BetterWB do extend usability of emulated / real Amiga. However, need of semi-manual installation with scripts inside emulator is slow and painful process. So what if there would be a possibility to call OS from "outside" via API provided by emulator?

Example: similar to logic of Ansible (actually the best would be to use Ansible directly), user would provide installation description in YAML format, Ansible-like tool would connect to API of UAE and then it would perform installation according to desired description. Ansible-like tool would be connected to external binary repository (with LHA/ZIP contents with Workbench versions, games and other software). Once Ansible finish the work, environment for Amiga would be prepared automatically.

Example: Following example above, one could write a module not only for LHA/ZIP packages, but perhaps also for standard Amiga Installer or even for the HD Toolbox. That way one could also prepare real harddrive attached to emulator (ie. CF card), prepare partitions, format them and install OS/Shapeshifter/PCTask/Whatever.

Goal: Fully automated and descriptive process of Amiga preparation, be it for emulator only or for real hardware. Instead of downloading packages like ClassicWB, one would only download newer version of an YML file and assuming valid access to the binary repository (aka package manager), deployment of new versions would be matter of seconds (no running GUI required, emulator would run headless).

**Comment by FrodeSolheim** [comment]
There are several ways to do something like this already, without extra support for the emulator itself. For example, the (virtual) serial port can be used to communicate with the outside. So anyone can make a client/server solution for this - a "server" running as an AmigaOS process reading commands from the serial port, for example: transfer file, extract file, etc.

So I don't see why special emulator support is needed here (there is also the possibility of using an uae-native bridge to make the communication faster than with the serial port, but the concept remains the same).
