### ISSUE TITLE
Closing FS-UAE with Cmd+Q conflicts with Dopus and CygnusEd usage

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#19]
Quitting FS-UAE by pressing Cmd+Q is handled automatically by SDL 2.0. SDL may have to be patched in order to allow overriding this behavior.

Still, it is perhaps a good idea to let the application quit with this standard key combo on OS X, but if possible, it would be nice with an option to disable it.

A SDL_HINT_HANDLE_OS_HOTKEYS has already been suggested: https://forums.libsdl.org/viewtopic.php?p=33644#33644.

**Comment by FrodeSolheim** [comment]
The solution for Cmd+Q is for me to create a patch for SDL 2.

**Comment by FrodeSolheim** [comment]
Fixed for upcoming FS-UAE releases by bundling with a patched SDL 2 version. Cmd+Q will be ignored by SDL 2, and, if full keyboard emulation is enabled, FS-UAE will not quit on Cmd+Q.

**Comment by FrodeSolheim** [comment]
Also patched SDL 2 to remove default Cmd+M, Cmd+H and Ctrl+Cmd+F keyboard shortcut handling!

**Comment by FrodeSolheim** [comment]
Fix can be tested with this version: http://fs-uae.net/stable/2.8.0u3/

**Comment by MagerValp** [comment]
Nice, thanks! The right cmd key works as RAmiga in every situation now, but the left cmd key seems to control emulator keyboard shortcuts all the time. Is this expected behavior? Specifically I still miss LAmiga-N/M.

**Comment by FrodeSolheim** [comment]
Press Cmd+K to enable full keyboard emulation. There is also an option to start in this mode by default, if you want to.

**Comment by FrodeSolheim** [comment]
https://github.com/FrodeSolheim/fs-uae/blob/master/doc/options/full_keyboard

**Comment by MagerValp** [comment]
Ah, my config is still from 2.6, so that fixed it. Thank you!
