### ISSUE TITLE
Using two mice / 2 player mode in Lemmings 1

### ISSUE THREAD

**Issue by Gagert** [FrodeSolheim/fs-uae#194]
This has been my main Amiga emulator for a while mainly because of the xinput support for games which supports a 2 player mode (I had some issues using multiple Xbox One gamepads on WinUAE).

There is however one case I had to give up getting to work properly, and that was using two mouses in Lemmings 1 for multiplayer. I tried writing this and that in the config text file for Lemmings, but even though I managed to get all the other 2 player games working with one Xbox One gamepad for each player, I could not manage to get two mouses to work seperately in the 2 player mode in Lemmings 1.

I suppose fs-uae as of now (fs-uae 2.9.7 dev3) doesn't support 2 player games where mouse is the controller device for both players?

**Comment by FrodeSolheim** [comment]
It should work, but it's been a while since I tested it. You are using Windows?

**Comment by FrodeSolheim** [comment]
You are right, there was infact a bug, the functionality was accidentally disabled. Is fixed now, will be part of 2.9.9.dev, coming soon :) Thanks for reporting!

**Comment by FrodeSolheim** [comment]
Todo: test in WIndows as well

**Comment by Gagert** [comment]
Wow; thanks in advance. Can't wait to test it out when the 2.9.9 dev build arrives :)

**Comment by FrodeSolheim** [comment]
Actually, it was only fixed for Linux / macOS. There is an additional problem causing it to not work on Windows. I have a theory about what the problem is, and how to fix it.

**Comment by FrodeSolheim** [comment]
Theory was correct. Multiple mice seems to work in Windows now :) (Fix will be included in 2.9.11dev).

**Comment by FrodeSolheim** [comment]
2.9.11dev is out with fix. Closing this issue.

**Comment by yukulele** [comment]
Hi, 
How to configure FS-UAE to use two mice?
On setting I can only select one mouse, and then both mice move the first cursor.

**Comment by FrodeSolheim** [comment]
Depends what operating system you use; you need access to raw mouse devices to see more than one mouse. Have you read the documentation at https://fs-uae.net/docs/mouse ?
