### ISSUE TITLE
Cant install on Ubuntu 19.04

### ISSUE THREAD

**Issue by QkiZMR** [FrodeSolheim/fs-uae#197]
Following error appears during install from deb package.
  File "/usr/share/fs-uae-launcher/OpenGL/GL/SGIX/async.py", line 58
    from OpenGL.raw.GL.SGIX.async import *
                                ^
SyntaxError: invalid syntax

**Comment by Rhialto** [comment]
I think that is because you're trying to use it with Python 3.7, where `async` is a new keyword.

I thought I reported that somewhere earlier, but I can't find it.

**Comment by FrodeSolheim** [comment]
New versions are coming soon which fixes the problem.

**Comment by FrodeSolheim** [comment]
This is fixed in the development versions (2.9.8dev+)

**Comment by QkiZMR** [comment]
I confirm, it's installed and working fine.

**Comment by FrodeSolheim** [comment]
Great :)
