### ISSUE TITLE
vsync breaks fs-uae-launcher

### ISSUE THREAD

**Issue by mistepien** [FrodeSolheim/fs-uae#221]
Linux with intel card.
After exit from fullscreen with vsync gui (fs-uae-launcher) is not responsive. But if you switch to console and back then everything is normal again.

**Comment by FrodeSolheim** [comment]
Hi, I'm not convinced this is a Launcher issue. It sounds like an issue with the driver / window system or desktop environment

**Comment by FrodeSolheim** [comment]
Closing because the issue could not be reproduced, and there isn't enough indication that the problem is with FS-UAE.
