### ISSUE TITLE
Compilation with gcc 10

### ISSUE THREAD

**Issue by lucag73** [FrodeSolheim/fs-uae#227]
GCC 10 (Fedora 32) fails to compile fs-uae since implicit narrowing from int to unsigned int is now considered an error.
Adding as flag -Wno-narrowing is enough as to complete compilation; however fs-uae fails to execute because of errors with [FSEMU] (this is a different issue, though).

I also include a copy of the error log during compilation here:

make[2]: Entering directory '/home/lucag/Src/EMU/fs-uae'
depbase=`echo src/sana2.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -DLINUX -DUAE -DFSUAE -fno-pie -fno-PIE  -I./flac/include -I./gen -I./src -I./src/jit -I./src/include -I./src/od-fs -I./src/od-fs/include -I./src/od-win32 -I./src/od-win32/caps -I./libfsemu/include -I./fsemu/src  -I./glad/include   -I./libudis86/include  -I./prowizard/include    -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread  -DLUA_USE_POSIX  -I/usr/include/AL -I/usr/include/libpng16   -I/usr/include/SDL2 -D_REENTRANT -I/usr/include/SDL2 -D_REENTRANT    -fno-strict-overflow -fno-strict-aliasing -Wno-format-truncation -Waddress -Werror=missing-declarations -Wpointer-arith -fvisibility=hidden -I/usr/include/mpeg2dec  -g -O2 -MT src/sana2.o -MD -MP -MF $depbase.Tpo -c -o src/sana2.o src/sana2.cpp &&\
mv -f $depbase.Tpo $depbase.Po
src/sana2.cpp: In function ‘uae_u32 dev_open_2(TrapContext*)’:
src/sana2.cpp:136:46: error: narrowing conversion of ‘-2146762751’ from ‘int’ to ‘unsigned int’ [-Wnarrowing]
  136 | #define S2_CopyToBuff           (S2_Dummy + 1)
      |                                              ^
src/sana2.cpp:494:9: note: in expansion of macro ‘S2_CopyToBuff’
  494 |    case S2_CopyToBuff:
      |         ^~~~~~~~~~~~~
src/sana2.cpp:137:46: error: narrowing conversion of ‘-2146762750’ from ‘int’ to ‘unsigned int’ [-Wnarrowing]
  137 | #define S2_CopyFromBuff         (S2_Dummy + 2)
      |                                              ^
src/sana2.cpp:497:9: note: in expansion of macro ‘S2_CopyFromBuff’
  497 |    case S2_CopyFromBuff:
      |         ^~~~~~~~~~~~~~~
src/sana2.cpp:138:46: error: narrowing conversion of ‘-2146762749’ from ‘int’ to ‘unsigned int’ [-Wnarrowing]
  138 | #define S2_PacketFilter         (S2_Dummy + 3)
      |                                              ^
src/sana2.cpp:500:9: note: in expansion of macro ‘S2_PacketFilter’
  500 |    case S2_PacketFilter:
      |         ^~~~~~~~~~~~~~~
make[2]: *** [Makefile:5540: src/sana2.o] Error 1

**Comment by lucag73** [comment]
I correct myself (in data.fs/ fs-uae actually works).

**Comment by musuruan** [comment]
Version 3.0.5 fixes this issue. See: https://github.com/FrodeSolheim/fs-uae/issues/224

**Comment by lucag73** [comment]
Very good. Thanks (and sorry for the noise).
I was following the master branch (where the bug is still here) but this is on fs-uae-3.0 so I missed it.
