### ISSUE TITLE
[ENHANCEMENT] Include @mattiasgustavsson 's scanlines shader

### ISSUE THREAD

**Issue by SylvainDebaudringhien** [FrodeSolheim/fs-uae#228]
@mattiasgustavsson created a really good looking scanlines shader:
![Capture-1](https://user-images.githubusercontent.com/12871704/81056752-5abc0c00-8ecb-11ea-8c37-fe6ea7ab91be.png)
https://github.com/mattiasgustavsson/steem-crt
https://mattiasgustavsson.itch.io/steem-crt

It is currently working with STEEM (ST) and DosBox.
It would be amazing to have it in FS-UAE! :)

(also suggested to WinUAE https://github.com/tonioni/WinUAE/issues/173 )

**Comment by FrodeSolheim** [comment]
There are several CRT shaders avilable for FS-UAE already, I have no opinion of whether this one is better or not, and I'm happy to include it if someone ports this to the (GPU) shader format FS-UAE uses. But I don't think it warrants keeping this as an open issue.
