### ISSUE TITLE
Dark mode on mac

### ISSUE THREAD

**Issue by quantum8** [FrodeSolheim/fs-uae#229]
I've just updated fs-uae to 3.0.5 from 3.0.2 on macOS 10.14.6 and dark mode doesn't work well.

See attached screenshot when running both versions side by side for the differences.

![Screen Shot 2020-05-13 at 9 07 38 am](https://user-images.githubusercontent.com/5791220/81754331-472b2980-94f9-11ea-94a8-8ad548b07ddc.png)

**Comment by drkvogel** [comment]
Same here (3.0.5 on MacOS 10.14.6).

I looked for an option to disable dark mode, but couldn't find one - I think this should be an option, at least.

Where can I download previous releases, e.g. 3.0.2 which it seems didn't have this problem?

**Comment by quantum8** [comment]
@drkvogel from the main website:
http://fs-uae.net/stable/

**Comment by FrodeSolheim** [comment]
This should actually be moved to the fs-uae-launcher project. Created https://github.com/FrodeSolheim/fs-uae-launcher/issues/97 there.

**Comment by FrodeSolheim** [comment]
This is fixed for FS-UAE Launcher 3.1. See here: https://eab.abime.net/showthread.php?t=108745
