### ISSUE TITLE
Is there any way that mouse/joystick could switch based on button press?

### ISSUE THREAD

**Issue by BrianGilbert** [FrodeSolheim/fs-uae#231]
On my real A1200 I have a hardware device that switches input between mouse and joystick when I press a button on the given device, eg:

-Click left mouse button input switches to mouse
-Click joystick button input switches to Joystick

It's kinda like this device:
https://amigastore.eu/en/653-mouse-and-joystick-auto-switcher.html

Would it be possible to add this type of functionality in FS-UAE so that we don't need to jump to settings to be able to enable a secondary joystick when in a game, then again to re-enable mouse after I finish playing?

**Comment by mithrendal** [comment]
I think there is already a setting for this automatic joystick/ mouse switching... I had  need for it too and then frode implemented that switching feature long ago... hope it is still there ...

**Comment by BrianGilbert** [comment]
@mithrendal don't suppose you can point me in the right direction to make use of it??

**Comment by mithrendal** [comment]
![74BA43BC-1C49-4BAA-8492-23FA04385690](https://user-images.githubusercontent.com/17108995/86335816-4a1bde00-bc4f-11ea-9356-3aeba34ecd87.jpeg)

**Comment by BrianGilbert** [comment]
@mithrendal Don't suppose you know what that writes to the config, option doesn't appear in the UI on Mac or Linux (Amiberry) versions of FS-UAE

**Comment by mithrendal** [comment]
Try joystick_port_0_autoswitch


Above screenshot is mac too. Maybe older version?

**Comment by FrodeSolheim** [comment]
The default is that this is enabled. If I recall correctly, it (only) works if you start FS-UAE with mouse port in joystick mode! Due to this option, you can still use the mouse (mode will switch automatically) and the selected joystick (mode will switch back to joystick when needed).

**Comment by BrianGilbert** [comment]
@FrodeSolheim so I just set Mouse to the joystick in the config, and it will switch to mouse automatically when required?

**Comment by FrodeSolheim** [comment]
Correct (set joystick_port_0_mode = joystick)

**Comment by mithrendal** [comment]
You will see screen overlay text which tells you when it switches...

**Comment by BrianGilbert** [comment]
testing now

**Comment by BrianGilbert** [comment]
![IMG_7715](https://user-images.githubusercontent.com/114017/86348909-b32d4100-bca3-11ea-84f3-f971b4d60b32.JPG)
@FrodeSolheim doesn't seem to be switching, if I set the default dropdown to Mouse then I can use the joystick to mobvew the pointer though.

**Comment by FrodeSolheim** [comment]
@BrianGilbert This is not a screenshot of FS-UAE...

**Comment by BrianGilbert** [comment]
my apologies, I thought it was what Amiberry was based on, guess this can be closed then.
