### ISSUE TITLE
FreeBSD: joystick unknown.conf

### ISSUE THREAD

**Issue by frakswe** [FrodeSolheim/fs-uae#234]
Hey,
On FreeBSD the file in /FS-UAE/Controllers isn't generated with freebsd in the filename:

joystick_0_12_4_1_0_unknown.conf

i need to manually rename it to: 

"joystick_0_12_4_1_0_freebsd.conf"

normal joystick mode work fine without doing this but then i can't use more than up/down/left/right and fire on a gamepad (can't use cd32 mode etc).

**Comment by FrodeSolheim** [comment]
Hmm, if the bug is with the creation of the config file, then I guess it's rather a FS-UAE Launcher issue and should be moved there.

**Comment by FrodeSolheim** [comment]
I created https://github.com/FrodeSolheim/fs-uae-launcher/issues/98 in place of this.
