### ISSUE TITLE
fs_utf8_to_latin1 output lengths can differ from input

### ISSUE THREAD

**Issue by PowderedToastMan** [FrodeSolheim/fs-uae#245]
Within [nname_to_aname](https://github.com/FrodeSolheim/fs-uae/blob/1572da320030b5f762ee19a5db2b8cefbd74886c/src/od-fs/fsdb_host.cpp#L315), strlen of nname is used in a for loop for conversion purposes.
https://github.com/FrodeSolheim/fs-uae/blob/1572da320030b5f762ee19a5db2b8cefbd74886c/src/od-fs/fsdb_host.cpp#L317-L324
However, the result of `fs_utf8_to_latin1` isn't guaranteed to be the same as the input.  This will causes an invalid write when the result is smaller than the input.

Example:  `env-handler_español.doc`
`strlen(nname)` is 24
`strlen(cresult)` is 23

https://github.com/FrodeSolheim/fs-uae/blob/1572da320030b5f762ee19a5db2b8cefbd74886c/src/od-fs/fsdb_host.cpp#L331-L342

**Comment by PowderedToastMan** [comment]
I stink at git, otherwise I'd do a pull request.  [Here's](https://gist.github.com/PowderedToastMan/43b6eec648621f909e6ba80ffa552dc4) a patch.

**Comment by FrodeSolheim** [comment]
Thanks! I'll include the patch in FS-UAE - I've also confirmed that it fixes a crash reported here: http://eab.abime.net/showthread.php?t=105541

**Comment by FrodeSolheim** [comment]
Included in git master (and fs-uae-3.0) branch, thanks again!
