### ISSUE TITLE
fsemu/src/fsemu-glvideo.c:1478:33: error: use of undeclared identifier 'GL_RGB565'

### ISSUE THREAD

**Issue by rcampbel3** [FrodeSolheim/fs-uae#247]
Hi,

Building from source with gcc-9 on my old reliable Ubuntu 14.04 machine (yes, I know it's old).  I get this error:

fsemu/src/fsemu-glvideo.c: In function ‘fsemu_glvideo_display’:
fsemu/src/fsemu-glvideo.c:764:17: warning: unused variable ‘vsync_estimated_at’ [-Wunused-variable]
  764 |         int64_t vsync_estimated_at = FSEMU_FRAMEINFO(frame).vsync_estimated_at;
      |                 ^~~~~~~~~~~~~~~~~~
fsemu/src/fsemu-glvideo.c: In function ‘fsemu_glvideo_init’:
fsemu/src/fsemu-glvideo.c:1478:33: error: ‘GL_RGB565’ undeclared (first use in this function); did you mean ‘GL_RGB16’?
 1478 |         fsemu_glvideo.iformat = GL_RGB565;
      |                                 ^~~~~~~~~
      |                                 GL_RGB16
fsemu/src/fsemu-glvideo.c:1478:33: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:5330: fsemu/src/fsemu-glvideo.o] Error 1

**Comment by FrodeSolheim** [comment]
I will have a look at it :)

**Comment by FrodeSolheim** [comment]
@rcampbel3 It works for me here; fsemu-opengl.h was updated quite recently, is it possible you built an older version than the most recent commit available? Please pull down latest master and try again!

**Comment by FrodeSolheim** [comment]
Note; when I say it works for me, I actually tested on an Ubuntu 14.04 VM.

**Comment by FrodeSolheim** [comment]
Closing due to no response, you can re-open if the issue is still present.

**Comment by rcampbel3** [comment]
Thanks for testing this... My Ubuntu 14.04 machine is pretty customized and nonstandard now, but fs-uae had been building just fine for a long time on that machine. Just confirmed no build issues with latest source on Ubuntu 20.04. Guess it's time to upgrade. Thanks again.
