### ISSUE TITLE
Integrate latest changes from WinUAE

### ISSUE THREAD

**Issue by emoon** [FrodeSolheim/fs-uae#248]
Hi,

I wonder if there are any plans on integrate the latest changes from WinUAE? Toni has made lots of fixes in various parts of the code.

**Comment by FrodeSolheim** [comment]
Yes, the plan is to first got a dev release or two out for testing, then merge in code from the next WinUAE version. Do a dev release with that, and repeat until up 2 date :)

(I want to have dev releases out in between so people can help test when problems have been introduced, there's bound to be a few...)

**Comment by emoon** [comment]
Great! Thanks :)
