### ISSUE TITLE
Assertion error on fs-uae launch

### ISSUE THREAD

**Issue by vanfanel** [FrodeSolheim/fs-uae#273]
Hi there, this assertion error on SDL2 upon booting on the Pi4 with SDL2 2.0.16:

```
Assertion failure at SDL_GetDesktopDisplayMode_REAL (/root/src/SDL2-2.0.16/src/video/SDL_video.c:881), triggered 1 time:
  'displayIndex >= 0 && displayIndex < _this->num_displays'
```

Seems to be caused by iterating here:
https://github.com/FrodeSolheim/fs-uae/blob/b0bd935caffa1bba9bf5df77633698dd6bf4ba15/fsemu/src/fsemu-monitor.c#L162

Should iterate on `SDL_GetNumVideoDisplays ` instead.
Doing so fixes the issue.

Thanks!

**Comment by FrodeSolheim** [comment]
Fixed in https://github.com/FrodeSolheim/fs-uae/commit/3179b15a452aa55522039da6644e8705949bcc2e
