### ISSUE TITLE
Joystick mode = nothing appears to be ignored in 3.1.66 on Mac/Intel 

### ISSUE THREAD

**Issue by acf** [FrodeSolheim/fs-uae#297]
Hi Frode!

I use my Amiga (and emulator) for programming not games and had previously discovered I had to set the joystick port 0 to be nothing (no host device, no amiga device) to get my arrow keys working.  

I recently updated my version of UAE and my cursor keys seemed to have stopped working.  

All looks good in the launcher and in the config file.

<img width="748" alt="Screenshot 2022-01-08 at 17 45 27" src="https://user-images.githubusercontent.com/218/148654219-76ef95b5-fd6f-495c-845f-8573379a70b7.png">
<img width="364" alt="Screenshot 2022-01-08 at 17 45 33" src="https://user-images.githubusercontent.com/218/148654220-82cb1f8b-8d47-4b1c-a3cd-30c8af3f2ec1.png">

but when I run the emulator, no arrow keys.

Popping open the F12 menu I still have to manually set the joystick to NO HOST DEVICE / NONE to get my cursor keys.

<img width="574" alt="Screenshot 2022-01-08 at 17 46 59" src="https://user-images.githubusercontent.com/218/148654280-18805769-5932-4756-b2e2-63546e5d558e.png">
<img width="520" alt="Screenshot 2022-01-08 at 17 47 16" src="https://user-images.githubusercontent.com/218/148654281-cffdb6ea-0ba6-41ed-9885-de72c03753c7.png">

Wondering if I am doing something wrong, or if the config setting is being ignored ?

**Comment by FrodeSolheim** [comment]
Hi, this is not FS-UAE 3.1.66, this is FS-UAE 4.x preview, where port options are not working yet :)

**Comment by acf** [comment]
Aha!  I have somehow got the 3.1.66 launcher and a 4.x preview.  I must have done that while sleepwalking.   Thanks, and sorry for the noise :-)
