### ISSUE TITLE
Compiled but the font is broken? (Windows 10, MingW64)

### ISSUE THREAD

**Issue by MartyShepard** [FrodeSolheim/fs-uae#303]
Hello,

Hi. I compiled FS-Uae completely statically (without to use dll) and also a version with dynamic (dll) external libraries. The font is always broken. I had freshly installed MingW under Windows 10.

Could it have something to do with SDL2_Tff or Freetype ? I'm a little helpless. FS-UAE_4.0.71-master_Windows from CI Builds looks good
![Shot0238](https://user-images.githubusercontent.com/8560193/168426041-3102c643-5aa3-4497-9547-89d2ec7a81ee.png)
![Shot0239](https://user-images.githubusercontent.com/8560193/168426047-8a057327-8c93-4f1d-81fe-449c86336ad7.png)
.

**Comment by FrodeSolheim** [comment]
Hi, by coincidence, I noticed this issue today as well after updating my computer to Fedora Linux 36. So presumably, it is somehow related to an updated library. I don't know why yet, but since I'm also affected myself, I will definitively figure it out soon :)

**Comment by alic3woodstock** [comment]
I can confirm this bug using ubuntu 22.04 and arch linux

**Comment by FrodeSolheim** [comment]
A fixed has been pushed (https://github.com/FrodeSolheim/fs-uae/commit/86bf524c5f6e766a1904c237a87f4d1f282a137f)
