### ISSUE TITLE
Segfault on Debian testing with Nvidia driver 340.32

### ISSUE THREAD

**Issue by shmerl** [FrodeSolheim/fs-uae#31]
When running fs-uae on current Debian testing x86_64 (KDE), it always segfaults. Here is the backtrace from gdb:

<pre>Program received signal SIGSEGV, Segmentation fault.
__memmove_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1698
1698    ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S: No such file or directory.
(gdb) bt
#0  __memmove_ssse3_back () at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1698
#1  0x00007ffff27b8137 in ?? () from /usr/lib/libnvidia-glcore.so.340.32
#2  0x00007ffff27b8218 in ?? () from /usr/lib/libnvidia-glcore.so.340.32
#3  0x00007ffff69e06ad in ?? () from /usr/lib/libGL.so.1
#4  0x00007ffff7dea9bd in call_init (l=0x7ffff7fcf9f0, argc=argc@entry=1, argv=argv@entry=0x7fffffffe168, env=env@entry=0x7fffffffe178) at dl-init.c:64
#5  0x00007ffff7deaae3 in call_init (env=0x7fffffffe178, argv=0x7fffffffe168, argc=1, l=<optimized out>) at dl-init.c:36
#6  _dl_init (main_map=0x7ffff7ffe1a8, argc=1, argv=0x7fffffffe168, env=0x7fffffffe178) at dl-init.c:126
#7  0x00007ffff7ddd1ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#8  0x0000000000000001 in ?? ()
#9  0x00007fffffffe474 in ?? ()
#10 0x0000000000000000 in ?? ()</pre>

**Comment by FrodeSolheim** [comment]
The problem causing the crash has been identified... by NVIDIA :) FS-UAE bugfix release and more information at http://fs-uae.net/2015/01/27/fs-uae-2-4-3-released.
