### ISSUE TITLE
Warp Speed Toggle

### ISSUE THREAD

**Issue by frakswe** [FrodeSolheim/fs-uae#315]
Hi there.

I like to start with Warp speed enabled then manually disable it with alt+w when Workbench is finished loading.
I was wondering if there's a way to toggle it from within the emulated amiga somehow ? Maybe some peeking and poking?

Thanks

**Comment by frakswe** [comment]
Never mind, i lacked the program "uae-configuration".
`uae-configuration warp false` does the trick.

**Comment by ztronzo** [comment]
warp_mode=1

Starts in warp mode
