### ISSUE TITLE
Make F12 and F11 shortcut modifiers configurable

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#49]
Not all devices have F11 or F12 keys. It would be nice to be able to choose another modifier key.

**Comment by locksoft** [comment]
Hi Frode,

it would be very useful if all emulator key commands could be redirect to other keys, for example:

keyboard_key_escape = action_key_f12

Because on mac usually all Function keys are already assigned to something (my F12 is to raise the volume).
Yes, I know about CMD+F12 but, still, it's not very pratical during games. :)

Have a nice day

**Comment by ruci00** [comment]
Can you also make an option for completely disabling the menu (or unbinding F11 or F12)?

**Comment by FrodeSolheim** [comment]
Yes, I intend to make keyboard shortcuts more / fully configurable.

@ruci00 In this case - in the future - it will (probably) be possible to map F12 to action_none or something like that. What is the use case? Are you using FS-UAE as some of "kiosk" interface?

**Comment by ruci00** [comment]
@FrodeSolheim yeah, i explained that in other issue. `action_none` sounds great ;-)

**Comment by FrodeSolheim** [comment]
With commmit https://github.com/FrodeSolheim/fs-uae/commit/243d234e6a69ee7ac08c77b4492f1dd8879289bb, actions for F11 and F12 can be overriden.

Modifier key is fully configurable (at least not yet), but (Left) Alt / Cmd is added as a default modifier. Config and runtime option needed to toggle the use of this default modifier (so the Alt key can be freed for Amiga key emulation when needed).

**Comment by FrodeSolheim** [comment]
With commit https://github.com/FrodeSolheim/fs-uae/commit/e9a6146faa57ea59bb6c02a48a67c42b3affcf1d, the modifier key is configurable.
