### ISSUE TITLE
Implement support for action_pause

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#50]
Implementing support for action_pause will make it possible to re-assign the pause function to other key (combinations).

**Comment by cahirwpz** [comment]
I depend on pause key while coding demoscene effects. I use it to inspect the frame for visual bugs. Please implement this feature!

**Comment by FrodeSolheim** [comment]
You should already be able to use the pause/break key, or F12+p to pause the emulator. So I guess you are using a laptop (or similar) and want to have (easy access) to a one-key pause button instead of having to use a key combination?

**Comment by cahirwpz** [comment]
On Mon, Sep 14, 2015 at 4:07 PM, Frode Solheim <notifications@github.com>
wrote:

> You should already be able to use the pause/break key, or F12+p to pause
> the emulator. So I guess you are using a laptop (or similar) and want to
> have (easy access) to a one-key pause button instead of having to use a key
> combination?
>
Exactly. I'm running FS-UAE on MacBook pro. I frequently need to capture a
frame with pause key. It's important for me to freeze & unfreeze UAE
quickly while running an effect.

-- 
Kind regards
Krystian Bacławski

**Comment by FrodeSolheim** [comment]
Implemented in https://github.com/FrodeSolheim/fs-uae/commit/91f22f7079f3050fbb6cc0c23f02d48e2918372a, FS-UAE 2.5.41dev will be released shortly :)

**Comment by FrodeSolheim** [comment]
2.5.41dev released btw :)

**Comment by cahirwpz** [comment]
Works a treat! Thanks!

-- 
Kind regards
Krystian Bacławski
