### ISSUE TITLE
Missing Libscapsimage plugin?

### ISSUE THREAD

**Issue by gerroon** [FrodeSolheim/fs-uae#58]
Hi

I installed the dev repo on Debian Jessie. And I am getting this error on the screen when I start A500 emulation.

thanks

**Comment by hugo187** [comment]
I am having the same issue with the dev on OS X. I tried a few games from IPF floppies and none of them loaded. WHDLoad games worked though.

**Comment by FrodeSolheim** [comment]
You need the libcapsimage plugin for IPF floppy image support. See http://fs-uae.net/plugins. There's no pre-compiled version for Debian. See https://github.com/FrodeSolheim/fs-uae-plugin-capsimg for building it from source.

@hugo187 you can download the OS X plugin from http://fs-uae.net/plugins.
