### ISSUE TITLE
HRTmon Support

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#6]
"Please add the option to use the HRTmon freezer cartridge that is built into winUAE :) This is very useful for WHDload programming. Thanks!" (Issue imported from trac).

**Comment by cahirwpz** [comment]
HRTmon works well with following options in configuration file:

```
uae_cart_internal = hrtmon
keyboard_key_f8 = action_activate_cartridge
```

However I had to patch `ar.cpp` to make ROM visible at all times, cause I want to jump into it without pressing a button:

```
--- a/src/ar.cpp
+++ b/src/ar.cpp
@@ -2007,7 +2007,7 @@ void action_replay_memory_reset (void)
        if (hrtmemory) {
                hrtmon_hide (); /* It is never really idle */
                hrtmon_flag = ACTION_REPLAY_IDLE;
-               if (cart_type == CART_SUPER4)
+               if (1 || cart_type == CART_SUPER4)
                        hrtmon_map_banks ();
        }
 #endif
```

**Comment by FrodeSolheim** [comment]
There is also now and official option for it: `freezer_cartridge = hrtmon` (and `Alt+A` is default activation combo).
