### ISSUE TITLE
v2.4.3 (and v2.4.2 ?) not tagged in GitHub repo

### ISSUE THREAD

**Issue by dlitz** [FrodeSolheim/fs-uae#64]
Hi, there was a release announcement for v2.4.3 here: http://fs-uae.net/2015/01/27/fs-uae-2-4-3-released, but there's no corresponding tag pushed to the git repo at https://github.com/FrodeSolheim/fs-uae/.

There is also no v2.4.2 tag, although I'm not sure whether there was such a release.

I thought you might want to know.

**Comment by dlitz** [comment]
Ditto for v2.1.35dev

**Comment by FrodeSolheim** [comment]
I've pushed a tag for v2.4.3. 2.4.2 was not an official release. I'm not going to do anything about 2.1.x releases or earlier. Please see the commit log and check out specific commits if you are interested in those historical changes.
