### ISSUE TITLE
Bringing up UI with F12 should probably disable mouse grab

### ISSUE THREAD

**Issue by stuaxo** [FrodeSolheim/fs-uae#74]
I can never remember all the keys for UAE, but I can remember F12, maybe mouse grab should be temporarily disabled while the UI is up ?

**Comment by ruci00** [comment]
... and make mouse working in menu?

**Comment by FrodeSolheim** [comment]
Yes to both, really, just a matter of actually getting around to do it :)

**Comment by FrodeSolheim** [comment]
Mouse cursor should also be invisible while ungrabbed in this case - until you move it - so the mouse cursor isn't shown if you intent to use the keyboard (or especially a gamepad) to control the menu).

**Comment by FrodeSolheim** [comment]
Input grab disabled while menu is open implemented in https://github.com/FrodeSolheim/fs-uae/commit/243d234e6a69ee7ac08c77b4492f1dd8879289bb (scheduled for 2.7.3dev)
