### ISSUE TITLE
Support joystick hotplugging

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae#8]
When joysticks are connected while running the emulator, the joysticks should become available in the on-screen menu.

**Comment by ztronzo** [comment]
This would be a great feature and would be most useful when using it in netplay, as it will not require all players to disconnect and start all over when using the netplay feature when a a controller for any reason runs out of battery, times out or just gets reconnected for any reason.

**Comment by rofl0r** [comment]
does SDL even support this ?

**Comment by ztronzo** [comment]
Perhaps best to have a manual option to refresh the input device list...  just in case any automation causes a glitch, delay or crash...

**Comment by FrodeSolheim** [comment]
Joystick/gamepad hotplugging is implemented in the master branch, so I'm closing this issue (thpough the new input system isn't completely done yet).
