### ISSUE TITLE
Internal TCP/IP stack doesn't allow to create non-blocking IO sockets

### ISSUE THREAD

**Issue by jens-maus** [FrodeSolheim/fs-uae#80]
I am using FS-UAE to debug my development on YAM and corresponding Amiga projects. However, regarding the internal TCP/IP stack of FS-UAE something seems to be severely different between FS-UAE and WinUAE as the internal TCP/IP stack of FS-UAE seems to be unable to create non-blocking IO socket connects. Here I am always receiving the following error message when trying to perform any TCP/IP connection using FS-UAE:

```
01:E|09:45:24.410243|    Connection.c:1225:couldn't establish non-blocking IO: 9
01:E|09:45:24.446610|    Connection.c:1261:ConnectToHost() connection error: -6
```

The code trying to setup a non-blocking IO connection on a socket is:

```
          long nonBlockingIO = 1;

          // now we set the socket for non-blocking I/O
          if(IoctlSocket(conn->socket, FIONBIO, (void *)&nonBlockingIO) != -1)
          {
            ...
          }
          else
          {
            E(DBF_NET, "couldn't establish non-blocking IO: %ld", Errno());
            conn->error = CONNECTERR_NO_NONBLOCKIO;
            break;
          }
```

Thus, the execution of ```IoctlSocket(conn->socket, FIONBIO, (void *)&nonBlockingIO)``` seems to be always returning -1 which actually signals an error when trying to set the socket to non blocking mode.

The question now is, what is different to WinUAE where non-blocking IO mode doesn't return an error as I thought FS-UAE and WinUAE shares the same kernel and TCP/IP stack.

**Comment by jens-maus** [comment]
After some short investigation of the relevant source code, I think I found the potential problem.

Have a look at the ```host_IoctlSocket()``` function in https://github.com/FrodeSolheim/fs-uae/blob/master/src/od-fs/bsdsocket_posix.cpp#L1589 and compare it to the same function in the windows host file https://github.com/FrodeSolheim/fs-uae/blob/master/src/od-win32/bsdsock.cpp#L1602

You will see that in the windows version of that file "sd" is incremented by one in the very beginning and in the posix version not (just +1 used). That means that in case ```sd==0``` line https://github.com/FrodeSolheim/fs-uae/blob/master/src/od-fs/bsdsocket_posix.cpp#L1626 will become true and an error will be returned. However, I do feel that it is perfectly valid that sd is zero. The only thing that needs to be changed is to remove the ```sd-1```statements in line 1636 and 1639 and then also remove the whole sd==0 if block with the warning and error return.

However, I am currently unable to verify that and it would be great if you could create a new development build with that change applied so that I can test it accordingly. Please note, that using non-blocking IO sockets is very uncommon in Amiga programs. That might be the reason why nobody else yet reported on that issue because most of the people might use the Windows version of FS-UAE or WinUAE and thus will not be affected by that bug.

**Comment by jens-maus** [comment]
Please note that it was actually easier to compile and test my own compiled fs-uae than I first thought. :) I thus have applied my suggested changes and verified that it actually results in having YAM finally working with a unix/posix version of FS-UAE. Therefore, I would highly appreciate it if you could merge my pull request accordingly and integrate it in some future FS-UAE release.

**Comment by FrodeSolheim** [comment]
Issue fixed in https://github.com/jens-maus/fs-uae/commit/9cfb86c7d41c7b7bdb478e6da87fb668e33d1722 :)
