### ISSUE TITLE
Serial port functionality should allow to setup a tcp socket 

### ISSUE THREAD

**Issue by jens-maus** [FrodeSolheim/fs-uae#82]
In WinUAE it is possible to use something like ```serial_port = TCP://0.0.0.0:1234``` and then use "telnet" to connect to that socket for retrieving all serial debug output/data in case of using something like kprintf() during Amiga development. FS-UAE currently doesn't support this feature. It has been, however, mentioned in https://github.com/FrodeSolheim/fs-uae/issues/78 that something like that could be implemented quite straight forward.

Please note that care should be taken that this will also work on an OS4/ppc UAE session because there serial port debugging is also a very common task when developing Amiga applications.

**Comment by FrodeSolheim** [comment]
Oops, I spoke too soon. I was thinking of the ENET (udp-based) serial support. Serial over TCP looks like a bit more work.

**Comment by jens-maus** [comment]
UDP support would also be sufficient for a start as long as I can catch the output with something like necat or so.

**Comment by FrodeSolheim** [comment]
I have more or less ported the TCP serial code from WinUAE to FS-UAE now, will probably have to tweak and test a bit more before it works.

(I guess there is no reason this shouldn't work for OS4 as well, since we are talking about hardware-level emulation)

**Comment by FrodeSolheim** [comment]
Works now (at least AROS kickstart logs stuff via serial over TCP/IP. Implemented in commit https://github.com/FrodeSolheim/fs-uae/commit/75118f6e5898bfbba38f0d11242760367bec5467
