### ISSUE TITLE
error: 'sockaddr_in' was not declared in this scope

### ISSUE THREAD

**Issue by Rhialto** [FrodeSolheim/fs-uae#83]
I'm packaging fs-uae-2.7.2dev for in pkgsrc-wip (now available via http://pkgsrc.org/wip/ ). Compiling on NetBSD I ran into the following:
```
--- src/support/socket.o ---
depbase=`echo src/support/socket.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; c++ -DHA
VE_CONFIG_H -I.   -DUAE -DFSUAE -I./flac/include  -I./gen -I./src -I./src/jit -I
./src/include  -I./src/od-fs -I./src/od-fs/include -I./src/od-win32  -I./src/od-
win32/caps -I./libfsemu/include   -I./manymouse   -I./src/slirp/include -I./libu
dis86/include   -I./prowizard/include -I./softfloat -I./libmpeg2/include -I/usr/
pkg/include -I/usr/X11R7/include -I/usr/include -I/usr/X11R7/include/libdrm -I/u
sr/pkg/include/SDL2 -I/usr/X11R7/include/freetype2 -I/usr/X11R7/include/freetype
2 -I/usr/X11R7/include  -D_REENTRANT -I/usr/X11R7/include  -pthread -I/usr/pkg/i
nclude/glib/glib-2.0 -I/usr/pkg/lib/glib-2.0/include -I/usr/pkg/include  -DLUA_U
SE_POSIX  -I/usr/pkg/include  -D_REENTRANT -I/usr/X11R7/include  -I/usr/pkg/include/libpng16   -D_REENTRANT -D_THREAD_SAFE -I/usr/pkg/include/SDL2 -I/usr/X11R7/include    -fno-strict-overflow  -Wmissing-declarations -Waddress -fvisibility=hidden   -O2 -I/usr/pkg/include -I/usr/X11R7/include -I/usr/include -I/usr/X11R7/include/libdrm -I/usr/pkg/include/SDL2 -I/usr/X11R7/include/freetype2 -MT src/support/socket.o -MD -MP -MF $depbase.Tpo -c -o src/support/socket.o src/support/socket.cpp && mv -f $depbase.Tpo $depbase.Po
--- src/support/socket.o ---
src/support/socket.cpp: In function 'uae_socket uae_socket_accept(uae_socket)':
src/support/socket.cpp:167:28: error: 'sockaddr_in' was not declared in this scope
src/support/socket.cpp:169:51: error: 'socketaddr' was not declared in this scope
*** [src/support/socket.o] Error code 1

make: stopped in /pkg_comp/obj/pkgsrc/wip/fs-uae-dev/default/fs-uae-2.7.2dev
1 error
``` 
Looking into this, I found that the only use of sockaddr_in is in this fragment:
```
uae_socket uae_socket_accept(uae_socket s)
{
        socklen_t sa_len = sizeof(SOCKADDR_INET);
        char socketaddr[sizeof(SOCKADDR_INET)];
        uae_socket result = accept(s, (struct sockaddr*) socketaddr, &sa_len);
        return result;
}
```
`sa_len` should be the value from `struct addrinfo.ai_addrlen`.
if you're not interested in the value, like here, just use a dummy size. My manual doesn't say what happens if the value is too small, so using a size at least big enough for IPv6 addresses is probably wise.

I stubbed in 64 and with that there were no more build complaints.

**Comment by rofl0r** [comment]
the right fix is probably to just ```#include <netinet/in.h>```

**Comment by Rhialto** [comment]
That would work too, for IPv4 connections, but not for IPv6 (unless the implementation happens to have lots of spare room in sockaddr_in).

**Comment by rofl0r** [comment]
usually one uses sockaddr_storage, to fit in both sockaddr_in and sockaddr_in6.

**Comment by FrodeSolheim** [comment]
@rofl0r using sockaddr_storage was a good tip.
@Rhialto can you check if the following patch is sufficient for NetBSD? https://github.com/FrodeSolheim/fs-uae/commit/a9cb4a242f09556c08ac268ab1ec80e9f7e833c5 (looks like sys/socket.h should define sockaddr_storage http://pubs.opengroup.org/onlinepubs/009695399/basedefs/sys/socket.h.html)

**Comment by Rhialto** [comment]
Yes, that looks sufficient. (given my build environment I just tested it by replacing the `socket.c` file in the ...dev release). `sys/socket.h` does indeed define `struct sockaddr_storage`. (well unless one starts using those things like `POSIX_SOURCE` etc but that is usually a bad idea anyway)
