### ISSUE TITLE
MAP_ANONYMOUS not portable

### ISSUE THREAD

**Issue by Rhialto** [FrodeSolheim/fs-uae#84]
This problem occurs only in release branch of fs-uae-2.6.1, not in the development 2.7.

`src/od-fs/mman.cpp` uses `MAP_ANONYMOUS` but this is not a portable value; the true name is `MAP_ANON`. You already noticed this because of the `#ifdef`:

```
#ifdef USE_MMAP
#ifdef MACOSX
#define MAP_ANONYMOUS MAP_ANON
#endif
#endif
```
but in fact it is Linux here which is deviating. Its manual says
```
       MAP_ANON
              Synonym for MAP_ANONYMOUS.  Deprecated.
```
but it does not justify this by referencing any authority. Since it is not a POSIX flag (http://pubs.opengroup.org/onlinepubs/9699919799/functions/mmap.html doesn't mention anything like it), one should go by the origin of the mmap system call:
```
HISTORY
     The mmap() interface was first designed in 4.2BSD.
```
and
```
           MAP_ANON            Map anonymous memory not associated with any
                               specific file.  The file descriptor is not used
                               for creating MAP_ANON regions, and must be
                               specified as -1.  The mapped memory will be
                               zero filled.
```
(from the NetBSD manual page.)
and in fact, using `MAP_ANON` does work on Linux.

I came across this issue while packaging this version for pkgsrc.

**Comment by FrodeSolheim** [comment]
Hi, as you noticed, this is no longer an issue with the development version where I already use MAP_ANON instead. I wasn't planning on changing this for 2.6.x. I assume you'll just patch this for 2.6 in the package for NetBSD.

**Comment by Rhialto** [comment]
Yes, that's what I have done. I mostly created the issue in case you'd want to bring anything similar back into the code. I'll close it now.
