### ISSUE TITLE
Support for disabling messages on screen

### ISSUE THREAD

**Issue by ruci00** [FrodeSolheim/fs-uae#86]
Hi, can you make an option in configuration for disabling messages and warnings on screen? Something like "quiet mode" or "disabled verbose mode". Thanks!

**Comment by FrodeSolheim** [comment]
First reaction is: sounds like a really bad idea (at least concerning warnings). Warnings are shown for a reason. But there can probably be reasons for wanting to surpress specific messages.

What is the use case? What message do you want to surpress, and why?

**Comment by ruci00** [comment]
I want to make a Linux distro with FS-UAE (because it's the newest and most updated UAE emulator for this OS), but I want everything hidden and transparent so user doesn't even see if he's running an emulator. Something like Amithlon, but more modern and better (support for AGA, more drivers, Live CD/USB etc.).

**Comment by FrodeSolheim** [comment]
But still, if there for some reason was a problem with the config, it would be better to display the message than to ignore it (and get useless bug reports).

Is there any message in particular which is a problem?

**Comment by ruci00** [comment]
Yeah, the message appears when switching to PPC ("notify_user 22"? I don't quite remember now)

**Comment by FrodeSolheim** [comment]
#22 is NUMSG_UAEBOOTROM_PPC "UAE boot ROM cannot be used with PPC native OS"

**Comment by FrodeSolheim** [comment]
Closing this issue since a use case (which is better than fixing the config) hasn't been provided.
