### ISSUE TITLE
Emulator freezes on changing screen resolution using uaegfx

### ISSUE THREAD

**Issue by gryf** [FrodeSolheim/fs-uae#97]
On new stable version: 2.6.2 (and latest development: 2.7.6) I've bumped at a bug, which doesn't occur on previous stable version (2.4.3): If you'll try to change resolution using uaegfx driver, emulated machine will hang.

The reproducing steps are as follows:
1. Prepare the simple config file, like one below:

    [fs-uae]
    amiga_model = A4000/040
    fast_memory = 4096

    hard_drive_0 = /tmp/amiga
    hard_drive_0_label = wb

    kickstart_file = kick31.rom
    uaegfx_card = 1

2. Install fresh WB 3.1
3. Install picasso96 package [following the abime guide](http://guide.abime.net/wb3.1/chap5.htm)
4. Try to change screen mode to something which use UAE display mode
5. Observe black screen :)

Logs will give something like:

    […]
    RTG mode mask: 212
    P96: Hardware sprite support disabled
    uaegfx.card magic code: 00F03000-00F0313E ABI=00238F5C
     1: 50001000  320x 200 UAE: 320x 200
     2: 50011000  320x 240 UAE: 320x 240
     3: 50091000  320x 256 UAE: 320x 256
    P96: Non-unique mode 640x360
     4: 50FF1000  640x 360 UAE: 640x 360
     5: 50021000  640x 400 UAE: 640x 400
     6: 50031000  640x 480 UAE: 640x 480
     7: 500A1000  640x 512 UAE: 640x 512
    P96: Non-unique mode 672x540
     8: 50FE1000  672x 540 UAE: 672x 540
    P96: Non-unique mode 800x450
     9: 50FD1000  800x 450 UAE: 800x 450
    P96: Non-unique mode 800x500
    10: 50FC1000  800x 500 UAE: 800x 500
    11: 50041000  800x 600 UAE: 800x 600
    P96: Non-unique mode 960x540
    12: 50FB1000  960x 540 UAE: 960x 540
    13: 508B1000 1024x 576 UAE:1024x 576
    P96: Non-unique mode 1024x600
    14: 50FA1000 1024x 600 UAE:1024x 600
    15: 50051000 1024x 768 UAE:1024x 768
    16: 508E1000 1280x 720 UAE:1280x 720
    17: 50071000 1280x1024 UAE:1280x1024
    P96: Non-unique mode 1344x1080
    18: 50F91000 1344x1080 UAE:1344x1080
    19: 50991000 1920x1200 UAE:1920x1200
    Display Size: 724x512 Offset: 6x36
    First: 44 Last: 300 MinV: 42 MaxV: 313 Min: 26
    Display Size: 640x512 Offset: 74x36
    First: 44 Last: 300 MinV: 42 MaxV: 313 Min: 26
    grab input mode: 0
    grab input mode: 1
    Your Amiga program just did something terribly stupid 40000000 PC=00F0307A
    3FFFFFE0  0000 0000 0000 0000 0000 0000 0000 0000
    3FFFFFF0  0000 0000 0000 0000 0000 0000 0000 0000
    40000000  0000 0000 0000 0000 0000 0000 0000 0000
    40000010  0000 0000 0000 0000 0000 0000 0000 0000
    40000020  0000 0000 0000 0000 0000 0000 0000 0000
    00F0305A  0101 0101 0100 48E7 8000 A005 4A80 4CDF
    00F0306A  0001 6604 2F28 01BA 4E75 48E7 8000 A006
    00F0307A  4A80 4CDF 0001 6604 2F28 0182 4E75 48E7
    00F0308A  8000 A007 4A80 4CDF 0001 6604 2F28 0192
    00F0309A  4E75 48E7 8000 A008 4A80 4CDF 0001 6604
    00000000    2048K/1 =    2048K Chip memory
    00200000    4096K/1 =    4096K Fast memory
    00600000    6080K/0 =    6080K <none>
    00BF0000      64K/0 =      64K CIA
    00C00000    1024K/0 =    1024K Custom chipset
    00D00000     768K/0 =     768K <none>
    00DC0000      64K/0 =      64K Battery backed up clock (RF5C01A)
    00DD0000      64K/0 =      64K A4000 IDE
    00DE0000      32K/0 =      32K Motherboard Resources
    00DE8000      32K/0 =      32K <none>
    00DF0000      64K/0 =      64K Custom chipset
    00E00000     576K/0 =     576K <none>
    00E90000      64K/0 =      64K Filesystem autoconfig
    00EA0000     384K/0 =     384K <none>
    00F00000      64K/1 =      64K UAE Boot ROM
    00F10000     448K/0 =     448K <none>
    00F80000     512K/1 =     512K Kickstart ROM (FC24AE0D)
    =KS ROM v3.1 (A500,A600,A2000) rev 40.63 (512k)
    01000000     104M/0 =     104M <none>
    07800000       8M/1 =       8M RAMSEY memory (low)
    08000000    3952M/0 =    3952M <none>
    FF000000      64K/0 =      64K Autoconfig Z3
    FF010000   16320K/0 =   16320K <none>
    CPU halted: reason = 3 PC=00f0307a
    fs_emu_audio_resume_stream 0
    ERROR - Invalid RenderInfo memory area...

**Comment by gryf** [comment]
I have bisect the repository to find the changeset which introduced that behaviour. Unfortunately it turns out, that it was 771dde4, which do update to WinUAE 2820b1 :( the last working (in my env) commit, was 06af4ab.

If you need anything else to reproduce that behaviour, I can provide you with build logs, environment or anything you'll need to narrow down the issue.

BTW, on what environment and hardware are you testing the code?

**Comment by FrodeSolheim** [comment]
I mainly work on my Ubuntu Linux (x86-64) box, currently at 15.10. I have tried to reproduce, but have not been successful yet.

I think this line is somewhat interesting:

    Your Amiga program just did something terribly stupid 40000000 PC=00F0307A

**Comment by gryf** [comment]
I've been testing on Gentoo (which is always latest ;) and Ubuntu 14.04 LTS. I'm wondering if there could be some changes in dependent packages (IDK - sdl? mesa? libpng?). I'll try to quickly set up machine with Ubuntu 15.10 and see what I can discover. Nevertheless, I don't see any breaking changes on the commit 771dde4, so it's even more weird.

**Comment by gryf** [comment]
I've tested it against latest Ubuntu 15.10 64b, on two different machines than my primary one.
First one was the HP notebook with Intel graphics. Installed fresh Ubuntu 15.10, dependencies (am I missing anything?):

- git
- automake
- libtool
- build-essential
- libsdl2-dev
- libpng12-dev
- zlib1g-dev
- libglib2.0-dev
- libopenal-dev
- mesa-common-dev
- libglew-dev
- libmpeg2-4-dev

cloned the repo and built the fs-uae. Result was the same as I've got on my primary machine. Because I also have Intel graphics, I thought that maybe it's connected with the graphics. So I tried on the Sony Vaio notebook, which have Nvidia graphics, done the same (installing Ubuntu 15.10, proprietary Nvidia drivers, deps, git, clone, build and run) with the same result (fs-uae is locked, black screen, similar logs as I paste above)

So now this is really weird, and I'm stuck on the old version of fs-uae :(

**Comment by FrodeSolheim** [comment]
Hmm, looking at your config..:

    amiga_model = A4000/040

and log

    00F80000     512K/1 =     512K Kickstart ROM (FC24AE0D)
    =KS ROM v3.1 (A500,A600,A2000) rev 40.63 (512k)

I'm guessing this is the problem right there. Please pair your A4000 model with an A400 kickstart ROM instead of an A500/A600/A2000.

**Comment by gryf** [comment]
Actually, you were right! Changing the kickstart for the system to the right one done the trick.

Still, I'm surprised that the very same configuration works on fs-uae 2.4.x version fine, than on latest version not (starting with the commit mentioned above), while I've tested this very system and this particular failing kickstart against winuae (configuring similar as an A4000) which just works… So, just maybe, there is some regresion or bug after all, which is specific to fs-uae emulation implementation, while it's non-existent in winuae. Just a thought.

Anyway, the mystery is solved now, at least there is a workaround, so the bug can be closed. Thank you for your time!
