### ISSUE TITLE
Feature request: In emulation menu (F12) add a possibility to quit the emulation only (F12+Q)

### ISSUE THREAD

**Issue by ToKe79** [FrodeSolheim/fs-uae#98]
Useful when using arcade launcher and controlling with game pad - for example start button opens the menu (keyboard shortcut F12) and one could choose to quit the game and return to the arcade launcher, instead of using keyboard shortcut F12+Q, which means standing up from the couch / putting the game pad down... :-)
Pressing the "X" in top right corner quits the game and launcher too. So either it (the "X" in top right corner) should quit only the current emulation, or a new entry, for example below load/save state buttons (emulator control section) could be added:
--emulation control---
pause
load state
save state
quit <== here
---amiga control---
reset amiga
shut down <== or here
...

Thanks

**Comment by rootfather** [comment]
+1 for this.

**Comment by FrodeSolheim** [comment]
Using the X button in the top right corner (in FS-UAE) is only supposed to quit FS-UAE, not FS-UAE Arcade as well. If FS-UAE Arcade quits as well, that's a bug...

**Comment by FrodeSolheim** [comment]
@ToKe79 what OS/desktop environment are you using?

**Comment by ToKe79** [comment]
@FrodeSolheim I am using Windows 10 (Home, 64bit, low end notebook, 1GB RAM). Sometimes even F12+Q causes to quit both - emulator AND arcade launcher. I observed that when I have running both - the standard launcher (minimized) AND arcade launcher - F12+Q quits to arcade launcher (quits only emulation), but pressing X in emulation quits mostly to desktop (sometimes black screen, have to close using Alt+F4), but never to arcade launcher. I am using stable version of FS-UAE.

**Comment by FrodeSolheim** [comment]
I have been able to reproduce the problem where pressing X in FS-UAE with a joystick returns to a black screen in FS-UAE Arcade.

**Comment by FrodeSolheim** [comment]
http://eab.abime.net/showthread.php?t=80879

**Comment by FrodeSolheim** [comment]
This should be fixed in recent FS-UAE Arcade development version.
